# Semáforo de 4 niveles: 0 Verde · 1 Amarillo · 2 Naranja · 3 Rojo
# Nivel base = severidad de la regla (baja 0, media 1, alta 2, critica 3), salvo que la
# recomendación diga "no mezclar"/"evitar" (se sube). Cada medida activa baja N niveles;
# el piso es el mínimo al que puede llegar la regla aunque se apliquen todas las medidas.

NIVELES = [
  {"n": 0, "color": "verde", "nombre": "Verde", "lema": "Problema leve",
   "texto": "La mezcla genera el problema pero no es serio. Se puede preparar con buenas prácticas."},
  {"n": 1, "color": "amarillo", "nombre": "Amarillo", "lema": "Precaución",
   "texto": "Se puede mezclar solo aplicando las medidas indicadas y vigilando el caldo."},
  {"n": 2, "color": "naranja", "nombre": "Naranja", "lema": "Riesgo alto",
   "texto": "Mezclar solo si se aplican las correcciones; si no se puede, separar las aplicaciones."},
  {"n": 3, "color": "rojo", "nombre": "Rojo", "lema": "No mezclar",
   "texto": "No se recomienda preparar estos productos en el mismo caldo."},
]

# Medidas. tipo: producto (estabilizador que entra al tanque), practica (manejo) o ajuste
# (cambia un dato del caldo/agua y por eso la regla puede dejar de activarse).
MEDIDAS = {
 "antiesp": {"tipo":"producto","nombre":"Antiespumante","detalle":"Antiespumante siliconado (polidimetilsiloxano) en el paso 2, antes de los productos espumantes. Referencia 5-30 mL/100 L según etiqueta.","comp":"ady_antiespumante","paso":2},
 "ams": {"tipo":"producto","nombre":"Sulfato de amonio (AMS)","detalle":"Disuelto en el paso 2, antes de glifosato, 2,4-D y demás productos sensibles a la dureza. Dosis según análisis de agua (ver cálculo).","comp":"ady_ams","paso":2},
 "secu": {"tipo":"producto","nombre":"Secuestrante de dureza","detalle":"Quelante/secuestrante (EDTA, fosfonatos, citratos) en el paso 2. Es la alternativa al AMS cuando hay dicamba o cobre.","comp":"ady_secuestrante","paso":2},
 "buffer": {"tipo":"producto","nombre":"Regulador de pH (buffer)","detalle":"Llevar el agua al pH objetivo de la mezcla antes de cargar los activos. No usar con cobre, dicamba, organosiliconados ni biológicos sensibles.","comp":"ady_acidificante","paso":2},
 "compat": {"tipo":"producto","nombre":"Compatibilizador","detalle":"Agente de compatibilidad / antiaglomerante para mezclas con sales y suspensiones o emulsiones. Se agrega al agua antes de los productos.","comp":"ady_compat","paso":2},
 "orden": {"tipo":"practica","nombre":"Orden de carga correcto","detalle":"Cargar en el orden que muestra la app y esperar la dispersión o disolución total de cada producto antes del siguiente."},
 "predil": {"tipo":"practica","nombre":"Pre-dilución","detalle":"Pre-diluir o pre-dispersar cada producto por separado en un balde con agua (nunca mezclar concentrados entre sí)."},
 "agua70": {"tipo":"practica","nombre":"Tanque al 50-70 % de agua","detalle":"Empezar a cargar con el tanque al 50-70 % de agua limpia y la agitación encendida."},
 "agit": {"tipo":"practica","nombre":"Agitación constante","detalle":"Mantener el caldo en movimiento moderado y continuo desde la carga hasta terminar la aplicación, también en traslados y pausas."},
 "jarra": {"tipo":"practica","nombre":"Prueba de jarra aprobada","detalle":"Prueba de jarra con el agua y las proporciones reales, sin grumos, capas, gel ni espuma persistente a los 15-30 min."},
 "dosisplena": {"tipo":"practica","nombre":"Dosis plena del producto afectado","detalle":"Usar la dosis alta de etiqueta del producto que pierde eficacia por antagonismo (p. ej. el graminicida o el glifosato)."},
 "lavado": {"tipo":"practica","nombre":"Triple lavado del equipo","detalle":"Triple lavado con limpiador de tanques; filtros, pastillas y mangueras desarmados y lavados."},
 "fitotest": {"tipo":"practica","nombre":"Prueba en franja chica","detalle":"Aplicar primero en una franja pequeña del cultivo y observar 3-5 días."},
 "dosismin": {"tipo":"practica","nombre":"Dosis mínima de aceite/penetrante","detalle":"Bajar el aceite u organosiliconado a la dosis mínima de etiqueta."},
 "recalc": {"tipo":"practica","nombre":"Dosis total recalculada","detalle":"Sumar el activo que aportan todos los productos y ajustar para no superar la dosis de etiqueta."},
 "etiqueta": {"tipo":"practica","nombre":"La etiqueta autoriza la mezcla","detalle":"La etiqueta (o el fabricante del biológico) indica expresamente que la mezcla es compatible."},
 "lento": {"tipo":"practica","nombre":"Agregar lento y al final","detalle":"Espolvorear o verter despacio con agitación máxima, al final de la carga."},
 # Ajustes: cambian el dato de entrada efectivo
 "inmed": {"tipo":"ajuste","nombre":"Aplicar enseguida","detalle":"No dejar el caldo en reposo: preparar solo la carga que se aplica y salir a aplicar (≤ 1 h en el tanque).","ajusta":{"horas_en_tanque":0.5}},
 "vol": {"tipo":"ajuste","nombre":"Subir a 100 L/ha","detalle":"Aumentar el volumen de caldo a 100 L/ha (diluye sales y formulados).","ajusta":{"volumen_L_ha":100}},
 "aguatemp": {"tipo":"ajuste","nombre":"Agua entre 15 y 25 °C","detalle":"Usar agua templada (sin frío ni calor extremo).","ajusta":{"temperatura_C":20}},
 "agualimpia": {"tipo":"ajuste","nombre":"Agua limpia","detalle":"Agua filtrada o decantada, sin arcilla en suspensión.","ajusta":{"turbidez":"baja"}},
 "declor": {"tipo":"ajuste","nombre":"Agua sin cloro","detalle":"Reposar el agua 24 h o usar declorante antes del biológico.","ajusta":{"cloro_mg_L":0}},
 "horario": {"tipo":"ajuste","nombre":"Aplicar en horas frescas","detalle":"Aplicar temprano o al atardecer, con menos de 30 °C (Ley 3742/09: no aplicar con más de 32 °C).","ajusta":{"temperatura_ambiente_C":25}},
 "agitmod": {"tipo":"ajuste","nombre":"Agitación moderada","detalle":"Movimiento visible en la superficie sin turbulencia ni recirculación excesiva.","ajusta":{"agitacion":"normal"}},
}

# Regla: [nivel_base (None = según severidad), piso, {medida: niveles que baja}]
REGLAS = {
 "Q01":[None,0,{"orden":2,"predil":1,"agua70":1,"jarra":1,"compat":1}],
 "Q02":[None,0,{"vol":2,"predil":1,"orden":1,"compat":1,"jarra":1}],
 "Q03":[None,0,{"ams":1,"secu":1,"agua70":1,"predil":1,"jarra":1}],
 "Q13":[None,1,{"vol":1,"predil":1,"jarra":1,"compat":1}],
 "Q04":[3,3,{}],
 "Q04b":[None,0,{"jarra":1,"predil":1}],
 "Q05":[None,1,{"secu":2,"jarra":1}],
 "Q06":[2,2,{}],
 "Q07":[None,0,{"aguatemp":1,"predil":1,"agit":1}],
 "Q08":[None,0,{"agit":1,"inmed":1,"predil":1}],
 "Q09":[None,0,{"orden":1,"jarra":1}],
 "Q10":[None,0,{"lento":1}],
 "Q11":[None,0,{"orden":1,"jarra":1,"predil":1}],
 "Q12":[None,0,{"jarra":1,"compat":1}],
 "E01":[None,0,{"antiesp":2}],
 "E02":[None,0,{"antiesp":1}],
 "W01":[None,0,{"ams":2,"secu":2}],
 "W02":[None,0,{"ams":1,"secu":1}],
 "W03":[None,0,{"buffer":2,"inmed":1}],
 "W04":[None,0,{"buffer":1,"inmed":1}],
 "W05":[2,2,{}],
 "W06":[None,1,{"inmed":1,"buffer":1}],
 "W07":[None,1,{"agualimpia":2,"dosisplena":1}],
 "W08":[None,0,{"ams":1,"secu":1}],
 "W09":[None,0,{"ams":1,"buffer":1}],
 "W10":[None,2,{"declor":2}],
 "W11":[None,0,{"aguatemp":1,"inmed":1}],
 "A01":[None,1,{"dosisplena":1,"ams":1}],
 "A02":[None,1,{"ams":1,"secu":1}],
 "A03":[None,0,{"dosisplena":1}],
 "A04":[2,2,{}],
 "A05":[3,3,{}],
 "A06":[3,3,{}],
 "A07":[3,3,{}],
 "A08":[None,1,{"secu":1}],
 "A09":[2,2,{}],
 "F01":[3,3,{}],
 "F02":[3,3,{}],
 "F03":[2,2,{}],
 "F04":[None,0,{"dosismin":1,"fitotest":1,"horario":1}],
 "F05":[None,0,{"fitotest":1,"etiqueta":1}],
 "D01":[None,0,{"inmed":1}],
 "D02":[None,0,{"horario":1}],
 "D03":[3,3,{}],
 "D04":[2,2,{}],
 "X01":[None,0,{"orden":1,"inmed":1,"agit":1,"jarra":1}],
 "X02":[None,0,{"aguatemp":1,"predil":1}],
 "X03":[None,0,{"agit":1,"inmed":1}],
 "X04":[None,0,{"lavado":1}],
 "P01":[3,3,{}],
 "P01b":[2,2,{}],
 "P02":[None,1,{"orden":1,"predil":1,"jarra":1}],
 "P03":[3,1,{"etiqueta":2}],
 "P04":[2,2,{}],
 "P05":[None,0,{"jarra":1}],
 "V01":[None,0,{"orden":1,"agit":1,"predil":1,"jarra":1,"vol":1}],
 "V02":[2,2,{}],
 "V02b":[None,0,{"orden":2}],
 "V03":[None,0,{"orden":1,"agua70":1}],
 "V04":[None,0,{"lento":1}],
 "S01":[None,0,{"secu":1,"jarra":1}],
 "S02":[None,0,{"predil":1,"jarra":1}],
 "S03":[None,0,{"agitmod":1}],
 "G01":[3,3,{}],
 "G02":[3,3,{}],
 "G03":[3,3,{}],
 "G04":[3,3,{}],
 "G05":[3,3,{}],
 "G06":[3,3,{}],
 "G07":[None,0,{"orden":1}],
 "K01":[None,1,{"inmed":2,"buffer":1}],
 "K02":[None,1,{"inmed":1}],
 "K03":[3,3,{}],
 "K04":[None,0,{"ams":1,"secu":1}],
 "K05":[None,1,{"dosisplena":1}],
 "K06":[None,1,{"horario":1}],
 "K07":[None,0,{}],
 "B01":[None,0,{"jarra":1,"etiqueta":1}],
 "B02":[None,2,{"inmed":2}],
 "B03":[2,2,{}],
 "A10":[None,1,{"dosisplena":1}],
 "A11":[None,0,{"dosisplena":1,"ams":1}],
 "F06":[None,0,{"horario":1}],
 "F07":[None,0,{"horario":1}],
 "F08":[None,0,{"buffer":1}],
 "C01":[None,0,{"lavado":1}],
 "C02":[None,0,{"lavado":2}],
 "M01":[None,0,{"recalc":2}],
 "M02":[None,0,{"jarra":1}],
 "M03":[None,1,{"jarra":1}],
 "M05":[None,1,{"predil":1,"jarra":1}],
}
