# Carry-over (efecto residual en el suelo) y selectividad de herbicidas por cultivo.
#
# CARRY: días mínimos orientativos entre la aplicación y la siembra de cada cultivo.
#   "g" = valor para gramíneas (maíz, trigo/avena, arroz, sorgo, caña, pasturas gramíneas)
#   "h" = valor para cultivos de hoja ancha (soja, girasol, canola, algodón, poroto, sésamo,
#         chía, mandioca, hortalizas, leguminosas forrajeras)
#   claves de cultivo = excepciones a esos valores
#   0 = sin restricción conocida · None = sin dato (consultar etiqueta)
#   "c" = confianza (alta/media/baja) · "n" = nota
# Fuentes: etiquetas de productos registrados en la región (Paraguay, Argentina, Brasil, EE. UU.),
# Embrapa Trigo (herbicidas en soja y cultivos sucesores), Aegro (residual de herbicidas),
# INTA (residualidad de hormonales en barbecho corto). La persistencia cambia con la dosis,
# la lluvia acumulada, la textura, el pH y la materia orgánica del suelo: con poca lluvia
# los intervalos se alargan. Ante la duda, bioensayo con el suelo del lote.

CULTIVOS = {
    "soja": "Soja", "maiz": "Maíz", "trigo": "Trigo / avena / cebada", "arroz": "Arroz",
    "sorgo": "Sorgo", "girasol": "Girasol", "canola": "Canola", "algodon": "Algodón",
    "poroto": "Poroto / frijol", "sesamo": "Sésamo", "chia": "Chía", "cana": "Caña de azúcar",
    "mandioca": "Mandioca", "hortalizas": "Hortalizas", "pastura_gram": "Pastura gramínea",
    "pastura_leg": "Leguminosa forrajera", "eucalipto": "Eucalipto / pino",
}
GRAM = ["maiz", "trigo", "arroz", "sorgo", "cana", "pastura_gram"]
HOJA = ["soja", "girasol", "canola", "algodon", "poroto", "sesamo", "chia", "mandioca", "hortalizas", "pastura_leg"]

SIN = {"g": 0, "h": 0, "c": "alta", "n": "Sin actividad en el suelo: no deja residuo para el cultivo siguiente."}

CARRY = {
    # sin residual
    "glifosato": SIN, "glufosinato": SIN, "glufosinato_p": SIN, "paraquat": SIN, "diquat": SIN,
    "carfentrazona": {"g": 0, "h": 0, "c": "media", "n": "Residual muy corto."},
    "piraflufen": {"g": 0, "h": 0, "c": "media", "n": "Residual muy corto."},
    "lactofen": {"g": 0, "h": 0, "c": "media", "n": "Residual corto."},
    "bentazona": {"g": 0, "h": 0, "c": "media", "n": "Sin residual relevante."},
    "msma": {"g": 0, "h": 0, "c": "baja", "n": ""},
    # hormonales
    "24d": {"g": 0, "h": 15, "maiz": 7, "algodon": 30, "hortalizas": 30, "canola": 30, "pastura_leg": 60, "c": "media",
            "n": "Barbecho corto: unos 15 días antes de sembrar soja o girasol (sal amina a dosis alta, 15 a 30 días). Necesita lluvia; en seco se alarga."},
    "dicamba": {"g": 0, "h": 30, "trigo": 15, "sorgo": 15, "arroz": 15, "hortalizas": 60, "c": "media",
                "n": "Soja y algodón no tolerantes: 30 días y al menos 25 mm de lluvia (salvo variedades con tecnología tolerante)."},
    "picloram": {"g": 90, "h": 730, "hortalizas": 730, "pastura_gram": 0, "c": "media",
                 "n": "Muy persistente. La etiqueta indica sembrar especies sensibles recién 2 años después de la última aplicación; a dosis de pasturas puede afectar soja, algodón, poroto y hortalizas hasta 3 años. Hacer bioensayo antes de sembrar hoja ancha."},
    "aminopiralida": {"g": 120, "h": 540, "pastura_gram": 0, "hortalizas": 730, "pastura_leg": 730, "c": "media",
                      "n": "Muy persistente: cultivos de hoja ancha al menos 18 meses y solo después de un bioensayo en el lote; también pasa por el estiércol de animales que comieron pasto tratado."},
    "clopiralida": {"g": 0, "h": 300, "canola": 0, "poroto": 540, "hortalizas": 540, "c": "media", "n": "Leguminosas y hortalizas muy sensibles."},
    "triclopir": {"g": 0, "h": 30, "hortalizas": 60, "c": "baja", "n": "Residual corto a moderado."},
    "fluroxipir": {"g": 0, "h": 120, "c": "media", "n": ""},
    "halauxifen": {"g": 0, "h": 14, "algodon": 30, "poroto": 270, "pastura_leg": 270, "hortalizas": 450, "sesamo": 450, "chia": 450, "mandioca": 450, "c": "media", "n": "Soja, girasol y canola: 14 días; algodón 30 días; poroto y leguminosas 9 meses; otros cultivos 15 meses (etiqueta Elevore)."},
    "florpirauxifen": {"g": None, "h": None, "c": "baja", "n": "Arroz: consultar etiqueta para cultivos siguientes."},
    "fluchloraminopyr": {"g": None, "h": None, "c": "baja", "n": "Molécula nueva: consultar etiqueta."},
    "quinclorac": {"g": 0, "h": 300, "hortalizas": 365, "c": "baja", "n": "Solanáceas (tomate, papa) muy sensibles."},
    # triazinas, ureas, triazinonas
    "atrazina": {"g": 120, "h": 210, "maiz": 0, "sorgo": 0, "cana": 0, "pastura_gram": 90, "algodon": 180, "trigo": 210, "c": "media",
                 "n": "Con dosis altas o año seco, soja y girasol pueden necesitar la campaña siguiente."},
    "simazina": {"g": 120, "h": 300, "maiz": 0, "cana": 0, "c": "media", "n": ""},
    "terbutilazina": {"g": 120, "h": 210, "maiz": 0, "sorgo": 0, "c": "baja", "n": ""},
    "ametrina": {"g": 120, "h": 180, "cana": 0, "maiz": 0, "c": "baja", "n": ""},
    "prometrina": {"g": 120, "h": 120, "algodon": 0, "c": "baja", "n": ""},
    "diuron": {"g": 120, "h": 180, "algodon": 0, "cana": 0, "c": "baja", "n": ""},
    "linuron": {"g": 120, "h": 120, "soja": 0, "hortalizas": 0, "c": "baja", "n": ""},
    "fluometuron": {"g": 120, "h": 120, "algodon": 0, "c": "baja", "n": ""},
    "tebutiuron": {"g": 730, "h": 730, "cana": 0, "pastura_gram": 0, "c": "media", "n": "Hasta 2 años para soja, poroto y maní."},
    "hexazinona": {"g": 365, "h": 365, "cana": 0, "eucalipto": 0, "c": "baja", "n": "Muy persistente."},
    "metribuzina": {"g": 120, "h": 365, "soja": 0, "hortalizas": 0, "cana": 0, "algodon": 120, "c": "media", "n": "Girasol y canola: 12 meses."},
    "amicarbazona": {"g": 180, "h": 180, "cana": 0, "c": "baja", "n": ""},
    # inhibidores de ALS
    "imazetapir": {"g": 300, "h": 300, "soja": 0, "poroto": 0, "trigo": 120, "c": "media",
                   "n": "Maíz, girasol, arroz y canola Clearfield toleran sin espera. Maíz convencional: unos 300 días."},
    "imazapic": {"g": 300, "h": 300, "cana": 0, "trigo": 120, "c": "media", "n": "Excepto caña y maní, unos 300 días."},
    "imazapir": {"g": 365, "h": 365, "c": "baja", "n": "Puede llegar a 2 o 3 años en cultivos sensibles. Cultivos Clearfield toleran."},
    "imazaquin": {"g": 300, "h": 300, "soja": 0, "trigo": 120, "algodon": 300, "hortalizas": 540, "pastura_leg": 540, "c": "media", "n": "Maíz: más de 300 días en años secos. Hortalizas y alfalfa: 18 meses."},
    "clorimuron": {"g": 60, "h": 120, "soja": 0, "poroto": 60, "algodon": 60, "canola": 300, "hortalizas": 300, "sorgo": 90, "arroz": 90, "c": "media",
                   "n": "Trigo, maíz, poroto y algodón: 60 días (Embrapa)."},
    "metsulfuron": {"g": 60, "h": 120, "trigo": 0, "soja": 60, "pastura_gram": 0, "canola": 300, "hortalizas": 300, "c": "media",
                    "n": "Persistencia mayor en suelos alcalinos y secos."},
    "clorsulfuron": {"g": 365, "h": 365, "trigo": 0, "c": "baja", "n": "Muy persistente en suelos alcalinos."},
    "iodosulfuron": {"g": 90, "h": 120, "trigo": 0, "c": "baja", "n": ""},
    "nicosulfuron": {"g": 120, "h": 300, "maiz": 0, "soja": 15, "sorgo": 300, "c": "media", "n": "Sorgo: 10 meses (18 meses en suelos con pH mayor a 7,5)."},
    "trifloxisulfuron": {"g": 120, "h": 240, "algodon": 0, "cana": 0, "c": "baja", "n": "Poroto: unos 8 meses."},
    "sulfometuron": {"g": 365, "h": 365, "eucalipto": 0, "c": "baja", "n": "Uso no agrícola y forestal: muy persistente."},
    "pirazosulfuron": {"g": 90, "h": 120, "arroz": 0, "c": "baja", "n": ""},
    "diclosulam": {"g": 300, "h": 300, "soja": 0, "trigo": 120, "poroto": 120, "girasol": 540, "canola": 540, "c": "media", "n": "No sembrar maíz, sorgo, girasol ni canola en la zafriña después de soja tratada (etiqueta Spider Paraguay); girasol recién a los 18 meses."},
    "cloransulam": {"g": 270, "h": 300, "soja": 0, "c": "baja", "n": "Maíz, sorgo y arroz: unos 9 meses (etiqueta de EE. UU.); verificar la etiqueta local."},
    "flumetsulam": {"g": 120, "h": 540, "soja": 0, "maiz": 0, "trigo": 120, "poroto": 120, "arroz": 180, "sorgo": 365, "canola": 780, "hortalizas": 780, "c": "media", "n": "Maíz y soja 0; trigo y poroto 4 meses; arroz 6; sorgo 12; algodón y girasol 18; otros cultivos 26 meses con bioensayo."},
    "penoxsulam": {"g": 90, "h": 120, "arroz": 0, "c": "baja", "n": ""},
    "bispiribac": {"g": 60, "h": 90, "arroz": 0, "c": "baja", "n": ""},
    "piribenzoxim": {"g": 60, "h": 90, "arroz": 0, "c": "baja", "n": ""},
    "flucarbazona": {"g": 120, "h": 270, "trigo": 0, "c": "baja", "n": ""},
    # PPO
    "sulfentrazona": {"g": 180, "h": 120, "soja": 0, "girasol": 0, "cana": 0, "trigo": 120, "algodon": 365, "hortalizas": 365, "eucalipto": 0, "c": "media",
                      "n": "Maíz y sorgo: 6 a 10 meses según lluvia. Algodón muy sensible."},
    "flumioxazin": {"g": 30, "h": 30, "soja": 0, "maiz": 7, "algodon": 14, "canola": 120, "hortalizas": 60, "eucalipto": 0, "c": "media", "n": "Residual corto a moderado."},
    "fomesafen": {"g": 150, "h": 300, "soja": 0, "poroto": 0, "algodon": 0, "trigo": 120, "c": "media", "n": "Maíz y sorgo: al menos 150 días (Embrapa)."},
    "saflufenacil": {"g": 0, "h": 0, "girasol": 120, "canola": 120, "algodon": 42, "hortalizas": 120, "c": "media", "n": "Soja y maíz sin espera a dosis de barbecho."},
    "oxifluorfen": {"g": 60, "h": 60, "eucalipto": 0, "c": "baja", "n": ""},
    "trifludimoxazin": {"g": None, "h": None, "c": "baja", "n": "Molécula nueva: consultar etiqueta."},
    "epyrifenacil": {"g": None, "h": None, "c": "baja", "n": "Molécula nueva: consultar etiqueta."},
    "flufenoximacil": {"g": None, "h": None, "c": "baja", "n": "Molécula nueva: consultar etiqueta."},
    # HPPD y DXS
    "mesotriona": {"g": 120, "h": 300, "maiz": 0, "sorgo": 0, "cana": 0, "poroto": 540, "hortalizas": 540, "canola": 540, "c": "media", "n": "Soja: unos 10 meses."},
    "isoxaflutol": {"g": 120, "h": 300, "maiz": 0, "cana": 0, "eucalipto": 0, "soja": 180, "hortalizas": 540, "c": "media", "n": "Soja: unos 6 meses; se reactiva con lluvias."},
    "topramezona": {"g": 90, "h": 540, "maiz": 0, "soja": 270, "c": "media", "n": "Soja: unos 9 meses."},
    "tembotriona": {"g": 120, "h": 540, "maiz": 0, "soja": 300, "c": "media", "n": "Soja: unos 10 meses."},
    "tolpiralato": {"g": None, "h": None, "maiz": 0, "c": "baja", "n": "Consultar etiqueta."},
    "clomazona": {"g": 270, "h": 365, "soja": 0, "algodon": 0, "arroz": 0, "cana": 0, "mandioca": 0, "trigo": 365, "c": "media",
                  "n": "Maíz y sorgo: 9 meses; trigo: 12 meses. Volatiliza: blanqueo en cultivos vecinos."},
    # VLCFA y microtúbulos
    "s_metolacloro": {"g": 0, "h": 0, "trigo": 135, "arroz": 270, "canola": 270, "sorgo": 135, "pastura_gram": 120, "c": "media", "n": "Trigo: unos 4,5 meses. Sorgo solo con semilla tratada con protector (fluxofenim)."},
    "metolacloro": {"g": 0, "h": 0, "trigo": 135, "arroz": 270, "canola": 270, "sorgo": 135, "pastura_gram": 120, "c": "media", "n": "Sorgo solo con semilla tratada con protector (fluxofenim)."},
    "acetocloro": {"g": 0, "h": 0, "trigo": 120, "c": "baja", "n": ""},
    "piroxasulfona": {"g": 0, "h": 0, "arroz": 300, "sorgo": 300, "canola": 300, "hortalizas": 300, "pastura_leg": 300, "c": "baja", "n": ""},
    "pendimetalina": {"g": 0, "h": 0, "trigo": 165, "sorgo": 300, "arroz": 300, "c": "media", "n": "Cereales de invierno: no sembrar en la misma campaña (unos 5,5 meses)."},
    "trifluralina": {"g": 365, "h": 0, "trigo": 165, "pastura_gram": 365, "c": "media", "n": "Maíz, sorgo y arroz: unos 12 meses."},
    "flurocloridona": {"g": None, "h": None, "girasol": 0, "c": "baja", "n": "Consultar etiqueta."},
    # graminicidas
    "cletodim": {"g": 30, "h": 0, "c": "media", "n": "Gramíneas cultivadas (maíz, trigo, sorgo, arroz, pasturas): unos 30 días."},
    "haloxifop": {"g": 60, "h": 0, "c": "baja", "n": ""},
    "quizalofop": {"g": 120, "h": 0, "c": "baja", "n": ""},
    "propaquizafop": {"g": 60, "h": 0, "c": "baja", "n": ""},
    "fenoxaprop": {"g": 30, "h": 0, "arroz": 0, "c": "baja", "n": ""},
    "clodinafop": {"g": 30, "h": 0, "trigo": 0, "c": "baja", "n": ""},
    "pinoxaden": {"g": 30, "h": 0, "trigo": 0, "c": "baja", "n": ""},
    "cihalofop": {"g": 30, "h": 0, "arroz": 0, "c": "baja", "n": ""},
    "metamifop": {"g": 30, "h": 0, "arroz": 0, "c": "baja", "n": ""},
    "propanil": {"g": 0, "h": 0, "c": "baja", "n": "Sin residual relevante."},
    "tiobencarb": {"g": 0, "h": 0, "c": "baja", "n": ""},
    "benazolin": {"g": None, "h": None, "c": "baja", "n": "Consultar etiqueta."},
}

# Selectividad sobre el cultivo actual (aplicación pre o postemergente del cultivo).
#   "post": cultivos que toleran la aplicación sobre el cultivo emergido
#   "pre": cultivos que toleran la aplicación en preemergencia
#   "tec": cultivos que solo toleran con una tecnología (evento o variedad)
SELECT = {
    "glifosato": {"post": [], "pre": "*", "tec": {"soja": "RR / Intacta", "maiz": "RR", "algodon": "RR", "canola": "RR"}},
    "glufosinato": {"post": [], "pre": "*", "tec": {"soja": "LL / Enlist E3", "maiz": "LL (o eventos con gen PAT)", "algodon": "LL / Enlist"}},
    "glufosinato_p": {"post": [], "pre": "*", "tec": {"soja": "LL / Enlist E3", "maiz": "LL (o eventos con gen PAT)", "algodon": "LL / Enlist"}},
    "paraquat": {"post": [], "pre": "*", "n": "Solo desecación o aplicación dirigida."},
    "diquat": {"post": [], "pre": "*", "n": "Solo desecación o aplicación dirigida."},
    "24d": {"post": ["maiz", "trigo", "arroz", "sorgo", "cana", "pastura_gram"], "pre": ["maiz", "trigo", "sorgo", "cana"], "tec": {"soja": "Enlist E3", "algodon": "Enlist"}},
    "dicamba": {"post": ["maiz", "trigo", "sorgo", "cana", "pastura_gram"], "pre": ["maiz", "trigo", "sorgo"], "tec": {"soja": "Xtend", "algodon": "Xtend"}},
    "picloram": {"post": ["pastura_gram", "trigo"], "pre": ["pastura_gram"]},
    "aminopiralida": {"post": ["pastura_gram"], "pre": ["pastura_gram"]},
    "fluroxipir": {"post": ["maiz", "trigo", "arroz", "sorgo", "pastura_gram"], "pre": []},
    "triclopir": {"post": ["arroz", "pastura_gram"], "pre": []},
    "clopiralida": {"post": ["maiz", "trigo", "canola", "pastura_gram"], "pre": []},
    "halauxifen": {"post": ["trigo"], "pre": []},
    "cletodim": {"post": HOJA + ["eucalipto"], "pre": []},
    "haloxifop": {"post": HOJA + ["eucalipto"], "pre": []},
    "quizalofop": {"post": HOJA, "pre": []},
    "propaquizafop": {"post": HOJA, "pre": []},
    "fenoxaprop": {"post": ["soja", "arroz", "poroto"], "pre": []},
    "clodinafop": {"post": ["trigo"], "pre": []},
    "pinoxaden": {"post": ["trigo"], "pre": []},
    "cihalofop": {"post": ["arroz"], "pre": []}, "metamifop": {"post": ["arroz"], "pre": []},
    "bispiribac": {"post": ["arroz"], "pre": []}, "penoxsulam": {"post": ["arroz"], "pre": ["arroz"]},
    "pirazosulfuron": {"post": ["arroz"], "pre": ["arroz"]}, "piribenzoxim": {"post": ["arroz"], "pre": []},
    "propanil": {"post": ["arroz"], "pre": []}, "quinclorac": {"post": ["arroz"], "pre": ["arroz"]},
    "tiobencarb": {"post": ["arroz"], "pre": ["arroz"]}, "florpirauxifen": {"post": ["arroz"], "pre": []},
    "bentazona": {"post": ["soja", "maiz", "arroz", "poroto", "trigo", "sorgo"], "pre": []},
    "fomesafen": {"post": ["soja", "poroto"], "pre": ["soja", "poroto", "algodon"]},
    "lactofen": {"post": ["soja"], "pre": []},
    "clorimuron": {"post": ["soja"], "pre": ["soja"]}, "cloransulam": {"post": ["soja"], "pre": ["soja"]},
    "imazetapir": {"post": ["soja", "poroto"], "pre": ["soja", "poroto"], "tec": {"maiz": "Clearfield", "girasol": "Clearfield", "arroz": "Clearfield", "canola": "Clearfield"}},
    "imazapic": {"post": ["cana"], "pre": ["cana"]}, "imazaquin": {"post": ["soja"], "pre": ["soja"]},
    "imazapir": {"post": [], "pre": [], "tec": {"maiz": "Clearfield", "girasol": "Clearfield", "arroz": "Clearfield"}},
    "diclosulam": {"post": [], "pre": ["soja"]}, "flumetsulam": {"post": ["soja", "maiz"], "pre": ["soja", "maiz"]},
    "nicosulfuron": {"post": ["maiz"], "pre": []},
    "metsulfuron": {"post": ["trigo", "pastura_gram"], "pre": ["trigo"]},
    "iodosulfuron": {"post": ["trigo"], "pre": []}, "clorsulfuron": {"post": ["trigo"], "pre": ["trigo"]},
    "flucarbazona": {"post": ["trigo"], "pre": []},
    "trifloxisulfuron": {"post": ["algodon", "cana"], "pre": []},
    "mesotriona": {"post": ["maiz", "cana"], "pre": ["maiz", "sorgo", "cana"]},
    "tembotriona": {"post": ["maiz"], "pre": []}, "topramezona": {"post": ["maiz"], "pre": []}, "tolpiralato": {"post": ["maiz"], "pre": []},
    "isoxaflutol": {"post": [], "pre": ["maiz", "cana", "eucalipto"]},
    "atrazina": {"post": ["maiz", "sorgo", "cana"], "pre": ["maiz", "sorgo", "cana"]},
    "terbutilazina": {"post": ["maiz", "sorgo"], "pre": ["maiz", "sorgo"]},
    "simazina": {"post": [], "pre": ["maiz", "cana"]},
    "ametrina": {"post": ["cana"], "pre": ["cana"]}, "amicarbazona": {"post": ["cana"], "pre": ["cana"]},
    "hexazinona": {"post": ["cana"], "pre": ["cana", "eucalipto"]}, "tebutiuron": {"post": [], "pre": ["cana"]},
    "diuron": {"post": [], "pre": ["algodon", "cana"]}, "fluometuron": {"post": [], "pre": ["algodon"]}, "prometrina": {"post": [], "pre": ["algodon"]},
    "msma": {"post": ["algodon", "cana"], "pre": []},
    "metribuzina": {"post": ["cana", "trigo"], "pre": ["soja", "cana", "hortalizas"]},
    "linuron": {"post": [], "pre": ["soja", "hortalizas"]},
    "sulfentrazona": {"post": [], "pre": ["soja", "cana", "girasol", "eucalipto"]},
    "flumioxazin": {"post": [], "pre": ["soja", "girasol", "eucalipto"]},
    "saflufenacil": {"post": [], "pre": ["soja", "maiz", "trigo", "sorgo"]},
    "carfentrazona": {"post": ["maiz", "trigo", "arroz"], "pre": "*"}, "piraflufen": {"post": [], "pre": "*"},
    "oxifluorfen": {"post": [], "pre": ["eucalipto", "hortalizas"]},
    "s_metolacloro": {"post": [], "pre": ["soja", "maiz", "algodon", "girasol", "poroto", "cana", "hortalizas"], "tec": {"sorgo": "semilla con protector (fluxofenim)"}},
    "metolacloro": {"post": [], "pre": ["soja", "maiz", "algodon", "girasol", "poroto", "cana"], "tec": {"sorgo": "semilla con protector (fluxofenim)"}},
    "acetocloro": {"post": [], "pre": ["maiz", "soja"]},
    "piroxasulfona": {"post": [], "pre": ["soja", "maiz", "trigo", "girasol", "algodon"]},
    "pendimetalina": {"post": [], "pre": ["soja", "maiz", "algodon", "girasol", "arroz", "poroto", "hortalizas", "cana"]},
    "trifluralina": {"post": [], "pre": ["soja", "algodon", "girasol", "poroto", "canola", "hortalizas"]},
    "clomazona": {"post": [], "pre": ["soja", "algodon", "arroz", "cana", "mandioca"]},
}

MOMENTOS = {
    "barbecho": "Barbecho / antes de sembrar",
    "pre": "Preemergencia del cultivo",
    "post": "Sobre el cultivo emergido",
    "desecacion": "Desecación antes de cosecha",
}
