# Reglas agregadas a la base: deriva, condiciones ambientales, evaporación y lluvia.
# Las condiciones usan valores que calcula la app a partir del panel "Condiciones ambientales":
# viento_kmh, HR, temperatura_ambiente_C, delta_T (temperatura de bulbo seco - bulbo húmedo),
# lluvia_h (horas hasta la lluvia prevista) y fuera_ley (Ley 3742/09, art. 63: T > 32 °C,
# HR < 60 % o viento > 10 km/h).

DERIVA_AI = ["24d", "dicamba", "picloram", "triclopir", "fluroxipir", "aminopiralida", "clopiralida",
             "clomazona", "halauxifen", "florpirauxifen", "fluchloraminopyr"]

REGLAS_EXTRA = [
 {"id": "AMB01", "tipo": "deriva", "severidad": "critica",
  "titulo": "Condiciones fuera de lo permitido (Ley 3742/09, art. 63)",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"fuera_ley": {"==": True}}},
  "mecanismo": "Con más de 32 °C, menos de 60 % de humedad relativa o viento de más de 10 km/h, las gotas se evaporan o son arrastradas fuera del lote: deriva hacia cultivos, casas y cursos de agua, y pérdida de eficacia.",
  "recomendacion": "No aplicar. Esperar temperatura ≤ 32 °C, humedad ≥ 60 % y viento entre 3 y 10 km/h (temprano a la mañana o al atardecer, sin inversión térmica).",
  "confianza": "alta", "problemas": ["PR32", "PR33"]},
 {"id": "DR01", "tipo": "deriva", "severidad": "media",
  "titulo": "Viento moderado (6 a 10 km/h): riesgo de deriva",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"viento_kmh": {">": 6, "<=": 10}}},
  "mecanismo": "Las gotas menores de 150 µm se desplazan varios metros con viento moderado; el riesgo aumenta con botalón alto, presión alta y pastillas de gota fina.",
  "recomendacion": "Agregar antideriva al final de la carga, usar pastillas de inducción de aire (gota gruesa), bajar el botalón a 50 cm y dejar una franja sin aplicar del lado de cultivos sensibles.",
  "confianza": "alta", "problemas": ["PR32"]},
 {"id": "DR02", "tipo": "deriva", "severidad": "alta",
  "titulo": "Herbicidas hormonales o volátiles: daño por deriva a cultivos vecinos",
  "condiciones": {"presentes": [{"ai": DERIVA_AI, "volatil": True}], "agua": {}, "caldo": {}},
  "mecanismo": "Auxínicos (2,4-D, dicamba, picloram, triclopir) y clomazona dañan cultivos sensibles (algodón, soja no tolerante, hortalizas, frutales, eucalipto) con pocas gotas; los ésteres y el dicamba además se volatilizan con calor.",
  "recomendacion": "Antideriva en el caldo, pastillas de gota gruesa, viento de 3 a 10 km/h alejándose de los cultivos sensibles, nunca con calor o inversión térmica; preferir formulaciones de baja volatilidad (sal colina o amina en vez de éster).",
  "confianza": "alta", "problemas": ["PR32", "PR17"]},
 {"id": "DR03", "tipo": "deriva", "severidad": "media",
  "titulo": "Organosiliconado en el caldo: gotas más finas",
  "condiciones": {"presentes": [{"adyuvante": ["ady_organosiliconado"]}], "agua": {}, "caldo": {}},
  "mecanismo": "Los organosiliconados bajan mucho la tensión superficial: el chorro se rompe en gotas más chicas, que derivan y se evaporan más.",
  "recomendacion": "Usar pastillas de inducción de aire y agregar antideriva compatible; evitar con viento > 6 km/h.",
  "confianza": "media", "problemas": ["PR32", "PR30"]},
 {"id": "DR04", "tipo": "deriva", "severidad": "media",
  "titulo": "Volumen muy bajo (< 50 L/ha): gotas finas y evaporación",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"volumen_L_ha": {"<": 50}}},
  "mecanismo": "Para cubrir con poco caldo se usan pastillas de gota fina: más deriva y más evaporación antes de llegar al blanco.",
  "recomendacion": "Subir el volumen, usar antideriva y antievaporante, y aplicar con humedad alta.",
  "confianza": "alta", "problemas": ["PR32", "PR33"]},
 {"id": "DR05", "tipo": "deriva", "severidad": "alta",
  "titulo": "Viento calmo (< 3 km/h): posible inversión térmica",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"viento_kmh": {"<": 3}}},
  "mecanismo": "Con calma, al amanecer o al atardecer, el aire frío queda pegado al suelo: las gotas finas quedan suspendidas y se desplazan lejos horas después.",
  "recomendacion": "No aplicar con calma total ni con niebla o humo que queda a ras del suelo; esperar viento constante de 3 a 10 km/h.",
  "confianza": "alta", "problemas": ["PR32"]},
 {"id": "EV01", "tipo": "deriva", "severidad": "media",
  "titulo": "Delta T entre 8 y 10: evaporación rápida de gotas",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"delta_T": {">": 8, "<=": 10}}},
  "mecanismo": "El Delta T (diferencia entre temperatura y temperatura de bulbo húmedo) mide qué tan rápido se evapora el agua: entre 2 y 8 es lo ideal; por encima de 8 las gotas finas se achican y derivan.",
  "recomendacion": "Agregar antievaporante o aceite, usar gota gruesa y aplicar en horas más frescas.",
  "confianza": "alta", "problemas": ["PR33", "PR32"]},
 {"id": "EV02", "tipo": "deriva", "severidad": "alta",
  "titulo": "Delta T mayor a 10: no aplicar",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"delta_T": {">": 10}}},
  "mecanismo": "Con Delta T mayor a 10 la evaporación es tan rápida que gran parte del caldo no llega al blanco.",
  "recomendacion": "Suspender la aplicación hasta que baje la temperatura o suba la humedad.",
  "confianza": "alta", "problemas": ["PR33"]},
 {"id": "LL01", "tipo": "manejo", "severidad": "media",
  "titulo": "Lluvia prevista en menos de 2 horas: lavado del producto",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"lluvia_h": {"<": 2}}},
  "mecanismo": "Los productos necesitan un tiempo sin lluvia para secarse o absorberse (de 1 a 6 h según el activo y la formulación); la lluvia los lava de la hoja.",
  "recomendacion": "Agregar adherente o aceite según etiqueta, o postergar la aplicación; respetar el período libre de lluvia de cada etiqueta.",
  "confianza": "media", "problemas": ["PR33"]},
]

# [nivel_base (None = según severidad), piso, {medida: niveles que baja}]
SEMAFORO_EXTRA = {
 "AMB01": [3, 3, {}],
 "DR01": [None, 0, {"antideriva": 1, "pastillas": 1, "botalon": 1}],
 "DR02": [None, 1, {"antideriva": 1, "pastillas": 1}],
 "DR03": [None, 0, {"antideriva": 1, "pastillas": 1}],
 "DR04": [None, 0, {"antideriva": 1, "antievap": 1, "pastillas": 1, "vol": 1}],
 "DR05": [2, 2, {}],
 "EV01": [None, 0, {"antievap": 1, "pastillas": 1, "horario": 1}],
 "EV02": [2, 2, {}],
 "LL01": [None, 0, {"adherente": 1}],
}

MEDIDAS_EXTRA = {
 "antideriva": {"tipo": "producto", "nombre": "Antideriva", "detalle": "Polímero o goma guar antideriva: agranda las gotas. Va al final de la carga, espolvoreado o vertido despacio con agitación.", "comp": "ady_antideriva", "paso": 9},
 "adherente": {"tipo": "producto", "nombre": "Adherente", "detalle": "Adherente o aceite que mejora la resistencia al lavado por lluvia. Va al final de la carga.", "comp": "ady_adherente", "paso": 9},
 "antievap": {"tipo": "producto", "nombre": "Antievaporante", "detalle": "Adyuvante antievaporante (aceites, humectantes): reduce la pérdida de gotas con calor y baja humedad. Va con los adyuvantes.", "comp": "ady_antievap", "paso": 9},
 "pastillas": {"tipo": "practica", "nombre": "Pastillas de gota gruesa", "detalle": "Pastillas de inducción de aire o de baja deriva, a la presión que indica el fabricante para gota gruesa."},
 "botalon": {"tipo": "practica", "nombre": "Botalón bajo y velocidad moderada", "detalle": "Botalón a unos 50 cm del blanco y velocidad que no lo haga rebotar; franja sin aplicar del lado de cultivos sensibles."},
}

PROBLEMAS_EXTRA = [
 {"id": "PR32", "nombre": "Deriva de la pulverización (exoderiva)", "categoria": "equipo_seguridad",
  "que_es": "Parte del caldo sale del lote como gotas finas o vapor y cae sobre cultivos vecinos, viviendas, cursos de agua o personas.",
  "mecanismo": "Las gotas finas (< 150 µm) son arrastradas por el viento o quedan suspendidas con inversión térmica; los activos volátiles pasan a vapor con calor. Influyen el tamaño de gota (pastilla, presión, adyuvantes), la altura del botalón, la velocidad, el viento, la temperatura y la humedad.",
  "como_se_ve": ["Daño en cultivos vecinos días después (hojas deformadas, quemaduras)", "Niebla de gotas que se desplaza fuera del lote", "Menor control en el lote aplicado"],
  "causas": ["Viento mayor a 10 km/h o calma con inversión térmica", "Pastillas de gota fina o presión alta", "Botalón alto", "Temperatura alta y humedad baja", "Herbicidas hormonales o formulaciones volátiles (ésteres)"],
  "productos_y_condiciones_de_riesgo": "2,4-D, dicamba, picloram, triclopir, clomazona, glifosato y desecantes cerca de cultivos sensibles; organosiliconados; volúmenes bajos.",
  "prevencion": ["Respetar la Ley 3742/09: T ≤ 32 °C, HR ≥ 60 %, viento ≤ 10 km/h", "Viento de 3 a 10 km/h, alejándose de lo sensible", "Pastillas de inducción de aire y antideriva", "Botalón a 50 cm", "Zonas de amortiguamiento junto a cultivos sensibles, viviendas y agua"],
  "que_hacer_si_ocurre": ["Suspender la aplicación", "Registrar condiciones, productos y hora", "Avisar al vecino afectado y lavar el equipo"],
  "reglas_relacionadas": ["AMB01", "DR01", "DR02", "DR03", "DR04", "DR05", "EV01"]},
 {"id": "PR33", "nombre": "Evaporación de gotas y lavado por lluvia", "categoria": "equipo_seguridad",
  "que_es": "El producto no llega o no permanece en el blanco: las gotas se evaporan en el aire o la lluvia lo lava antes de que actúe.",
  "mecanismo": "Con Delta T alto (calor y aire seco) las gotas pierden agua en segundos y se vuelven más finas; con lluvia cercana el activo se lava antes de secarse o absorberse.",
  "como_se_ve": ["Control irregular o malo sin problemas en el tanque", "Más deriva de lo habitual", "Fallas después de una lluvia"],
  "causas": ["Delta T mayor a 8", "Humedad menor a 60 %", "Volumen bajo con gota fina", "Lluvia en las horas siguientes"],
  "productos_y_condiciones_de_riesgo": "Todos los productos foliares; más los de contacto y los que necesitan horas libres de lluvia.",
  "prevencion": ["Aplicar con Delta T entre 2 y 8", "Antievaporante o aceite según etiqueta", "Gota media a gruesa y volumen adecuado", "Consultar el período libre de lluvia de la etiqueta y usar adherente si corresponde"],
  "que_hacer_si_ocurre": ["Evaluar el control a los días indicados", "Si llovió dentro del período crítico, consultar la etiqueta antes de repetir"],
  "reglas_relacionadas": ["AMB01", "DR04", "EV01", "EV02", "LL01"]},
]
