# Para qué se usa cada principio activo (objetivos principales) y etiquetas de objetivo
# para la rotación de modos de acción. Orientativo: los usos autorizados de cada producto
# están en su etiqueta. Fuentes: clasificaciones HRAC (2024), IRAC (v11) y FRAC (2024),
# etiquetas registradas en la región y guías de manejo de resistencia.

OBJETIVOS = {
 # malezas
 "gram": "Gramíneas (pastos)", "hoja": "Hoja ancha", "cip": "Ciperáceas (tiririca)", "len": "Leñosas y arbustivas",
 "total": "Desecación / control total", "pre": "Preemergente (residual)",
 # plagas
 "lag": "Lagartas (orugas)", "chin": "Chinches", "pulg": "Pulgones y psílidos", "mbla": "Mosca blanca", "trips": "Trips",
 "acar": "Ácaros", "coleo": "Picudos, vaquitas y otros coleópteros", "suelo": "Plagas de suelo", "horm": "Hormigas cortadoras",
 "chich": "Chicharritas y salivazo", "minad": "Minadores", "cochi": "Cochinillas y escamas", "nema": "Nematodos",
 "alm": "Plagas de granos almacenados", "lang": "Langostas y tucuras", "term": "Termitas", "molu": "Caracoles y babosas",
 "roed": "Roedores",
 # enfermedades
 "roya": "Royas", "manch": "Manchas foliares (cercospora, mancha anillada, septoria…)", "oidio": "Oídio",
 "antr": "Antracnosis y tizones", "mild": "Mildiu y oomicetos (Phytophthora, Pythium)", "suelf": "Hongos de suelo y semilla",
 "scle": "Moho blanco (Sclerotinia)", "bact": "Bacteriosis", "podr": "Podredumbres de frutos y postcosecha",
 "piri": "Brusone del arroz (piricularia)",
 # otros
 "regu": "Regulación de crecimiento / maduración", "prot": "Protector (safener) de cultivo", "sine": "Sinergista",
}

USOS = {
 # ---------------- HERBICIDAS ----------------
 "24d": ("Hoja ancha en barbecho, maíz, trigo, arroz, caña y pasturas; complemento del glifosato contra buva (Conyza).", "hoja len"),
 "acetocloro": ("Preemergente de gramíneas y algunas hojas anchas de semilla chica en maíz y soja.", "pre gram"),
 "ametrina": ("Pre y postemergente de hoja ancha y gramíneas en caña de azúcar y cultivos perennes.", "hoja gram pre"),
 "amicarbazona": ("Pre y postemergente temprano de hoja ancha y gramíneas en caña de azúcar.", "pre hoja gram"),
 "aminopiralida": ("Hoja ancha y leñosas en pasturas (malezas de potrero), con picloram o 2,4-D.", "hoja len"),
 "atrazina": ("Pre y postemergente temprano de hoja ancha y algunas gramíneas en maíz, sorgo y caña.", "pre hoja gram"),
 "benazolin": ("Hoja ancha en canola/colza.", "hoja"),
 "bentazona": ("Postemergente de hoja ancha y ciperáceas en soja, arroz, maíz y poroto.", "hoja cip"),
 "bispiribac": ("Postemergente de gramíneas, hoja ancha y ciperáceas en arroz.", "gram hoja cip"),
 "carfentrazona": ("Hoja ancha de contacto: desecación (buva, nabo), postemergente y desecante de algodón.", "hoja total"),
 "cihalofop": ("Gramíneas (capín) en arroz.", "gram"),
 "cletodim": ("Graminicida postemergente en soja, algodón y hortalizas: capim amargoso, pasto colchón, maíz guacho.", "gram"),
 "clodinafop": ("Gramíneas (avena negra, raigrás) en trigo.", "gram"),
 "clomazona": ("Preemergente de gramíneas y algunas hojas anchas en soja, arroz, algodón y caña.", "pre gram hoja"),
 "clopiralida": ("Hoja ancha (compuestas, leguminosas) en cereales, canola y pasturas.", "hoja"),
 "cloransulam": ("Hoja ancha en soja (pre y post), incluida buva.", "hoja pre"),
 "clorimuron": ("Hoja ancha en soja (post), con efecto residual corto.", "hoja"),
 "clorsulfuron": ("Hoja ancha en trigo.", "hoja"),
 "dicamba": ("Hoja ancha y buva en barbecho y pasturas; volátil, cuidar deriva.", "hoja len"),
 "diclosulam": ("Preemergente de hoja ancha en soja (buva, caruru, poaia).", "pre hoja"),
 "diquat": ("Desecante de contacto: desecación pre-cosecha y control total.", "total"),
 "diuron": ("Pre y postemergente de hoja ancha y gramíneas en algodón, caña y cítricos; desecante en mezcla.", "pre hoja gram"),
 "epyrifenacil": ("Desecación de hoja ancha y gramíneas (PPO, molécula nueva).", "total hoja"),
 "fenoxaprop": ("Gramíneas en arroz y soja.", "gram"),
 "florpirauxifen": ("Gramíneas, hoja ancha y ciperáceas en arroz.", "hoja gram cip"),
 "flucarbazona": ("Gramíneas y hoja ancha en trigo.", "gram hoja"),
 "fluchloraminopyr": ("Hoja ancha y leñosas (auxínico nuevo).", "hoja len"),
 "flufenoximacil": ("Desecación de hoja ancha (PPO, molécula nueva).", "total hoja"),
 "flumetsulam": ("Hoja ancha en soja y maíz (pre).", "pre hoja"),
 "flumioxazin": ("Preemergente de hoja ancha y desecación (buva, caruru) en soja; también en eucalipto.", "pre hoja total"),
 "fluometuron": ("Pre y postemergente en algodón.", "pre hoja gram"),
 "flurocloridona": ("Preemergente de hoja ancha en girasol, papa y zanahoria.", "pre hoja"),
 "fluroxipir": ("Hoja ancha y leñosas en barbecho, maíz, trigo y pasturas (buva, malezas de potrero).", "hoja len"),
 "fomesafen": ("Postemergente de hoja ancha en soja y poroto (caruru, leche-leche).", "hoja"),
 "glifosato": ("Sistémico total: barbecho, desecación y post en cultivos RR; gramíneas y hoja ancha. Hay malezas resistentes (capim amargoso, buva, caruru, pata de gallina).", "total gram hoja"),
 "glufosinato": ("Control total de contacto: desecación y post en cultivos tolerantes (LL); útil contra resistentes a glifosato.", "total gram hoja"),
 "glufosinato_p": ("Igual que glufosinato, isómero activo (menor dosis).", "total gram hoja"),
 "halauxifen": ("Hoja ancha y buva en barbecho y trigo.", "hoja"),
 "haloxifop": ("Graminicida postemergente en soja y algodón (capim amargoso, maíz guacho).", "gram"),
 "hexazinona": ("Pre y postemergente en caña de azúcar y plantaciones forestales.", "pre hoja gram len"),
 "imazapic": ("Pre y post de gramíneas, hoja ancha y ciperáceas en caña y maní.", "pre gram hoja cip"),
 "imazapir": ("Control total y residual; maíz y girasol tolerantes (Clearfield), forestal.", "total gram hoja len"),
 "imazaquin": ("Hoja ancha en soja.", "hoja pre"),
 "imazetapir": ("Pre y post de hoja ancha y gramíneas en soja.", "hoja gram pre"),
 "iodosulfuron": ("Hoja ancha y raigrás en trigo.", "hoja gram"),
 "isoxaflutol": ("Preemergente de hoja ancha y gramíneas en maíz, caña y eucalipto.", "pre hoja gram"),
 "lactofen": ("Postemergente de hoja ancha en soja.", "hoja"),
 "linuron": ("Pre y post en zanahoria, papa y soja.", "pre hoja"),
 "mesotriona": ("Pre y post de hoja ancha en maíz y caña.", "hoja pre"),
 "metamifop": ("Gramíneas en arroz.", "gram"),
 "metolacloro": ("Preemergente de gramíneas en maíz, soja y otros.", "pre gram"),
 "metribuzina": ("Pre y post de hoja ancha en soja, trigo, papa y tomate.", "pre hoja"),
 "metsulfuron": ("Hoja ancha en trigo, barbecho y pasturas (malezas de potrero).", "hoja len"),
 "msma": ("Postemergente en algodón y caña.", "gram hoja cip"),
 "nicosulfuron": ("Gramíneas y algunas hojas anchas en maíz (post).", "gram hoja"),
 "oxifluorfen": ("Pre y post de hoja ancha en cebolla, frutales y forestales.", "pre hoja"),
 "paraquat": ("Desecante de contacto total: barbecho y desecación pre-cosecha.", "total"),
 "pendimetalina": ("Preemergente de gramíneas y hoja ancha de semilla chica.", "pre gram"),
 "penoxsulam": ("Gramíneas, hoja ancha y ciperáceas en arroz.", "gram hoja cip"),
 "picloram": ("Leñosas y hoja ancha en pasturas y barbecho (con 2,4-D); muy persistente.", "len hoja"),
 "pinoxaden": ("Gramíneas en trigo y cebada.", "gram"),
 "piraflufen": ("Desecante de contacto de hoja ancha; desecación de algodón.", "hoja total"),
 "pirazosulfuron": ("Hoja ancha y ciperáceas en arroz.", "hoja cip"),
 "piribenzoxim": ("Gramíneas y hoja ancha en arroz.", "gram hoja"),
 "piroxasulfona": ("Preemergente de gramíneas y hoja ancha en soja y maíz.", "pre gram hoja"),
 "prometrina": ("Preemergente en algodón.", "pre hoja gram"),
 "propanil": ("Postemergente de gramíneas en arroz.", "gram"),
 "propaquizafop": ("Graminicida postemergente en soja y hortalizas.", "gram"),
 "quinclorac": ("Capín y algunas hojas anchas en arroz.", "gram hoja"),
 "quizalofop": ("Graminicida postemergente en soja y hortalizas.", "gram"),
 "s_metolacloro": ("Preemergente de gramíneas en maíz, soja y hortalizas.", "pre gram"),
 "saflufenacil": ("Desecación de hoja ancha (buva) y preemergente.", "hoja total pre"),
 "simazina": ("Preemergente en maíz, caña, frutales y forestales.", "pre hoja gram"),
 "sulfentrazona": ("Preemergente de hoja ancha y tiririca en soja, caña y eucalipto.", "pre hoja cip"),
 "sulfometuron": ("Control total/preemergente en áreas forestales y no cultivadas.", "pre total"),
 "tebutiuron": ("Pre y control de leñosas en caña y pasturas.", "pre len hoja"),
 "tembotriona": ("Postemergente de hoja ancha y gramíneas en maíz.", "hoja gram"),
 "terbutilazina": ("Pre y post temprano en maíz.", "pre hoja gram"),
 "tiobencarb": ("Preemergente de gramíneas en arroz.", "pre gram"),
 "tolpiralato": ("Postemergente de hoja ancha y gramíneas en maíz.", "hoja gram"),
 "topramezona": ("Postemergente de gramíneas y hoja ancha en maíz.", "gram hoja"),
 "triclopir": ("Leñosas y hoja ancha en pasturas, forestal y arroz.", "len hoja"),
 "trifloxisulfuron": ("Hoja ancha y ciperáceas en algodón y caña.", "hoja cip"),
 "trifludimoxazin": ("Desecación y preemergente de hoja ancha (PPO).", "hoja pre"),
 "trifluralina": ("Preemergente de gramíneas en soja, algodón y hortalizas.", "pre gram"),
 # ---------------- FUNGICIDAS ----------------
 "azoxistrobina": ("Preventivo de amplio espectro: roya, manchas, antracnosis, tizones en soja, maíz, trigo y hortalizas.", "roya manch antr"),
 "azufre": ("Oídio y ácaros en frutales y hortalizas.", "oidio acar"),
 "benomil": ("Manchas, antracnosis y podredumbres; tratamiento de semillas.", "manch antr podr suelf"),
 "benzovindiflupir": ("Roya asiática y manchas en soja; manchas en maíz.", "roya manch"),
 "bixafen": ("Roya y manchas en soja y cereales (con protioconazol).", "roya manch"),
 "carbendazim": ("Manchas, antracnosis, moho blanco y semillas en soja y cereales.", "manch antr scle suelf"),
 "carboxina": ("Tratamiento de semillas: carbón y hongos de semilla.", "suelf"),
 "ciclobutrifluram": ("Nematodos y hongos de suelo (tratamiento de semillas).", "nema suelf"),
 "cimoxanil": ("Mildiu y tizón tardío en papa, tomate y vid.", "mild"),
 "ciproconazol": ("Roya y manchas en soja, café y cereales.", "roya manch oidio"),
 "cloro_activo": ("Desinfección de herramientas, superficies y agua.", "bact"),
 "clorotalonil": ("Multisitio protector: manchas, roya y antracnosis; socio antirresistencia.", "manch roya antr"),
 "cobre": ("Multisitio: bacteriosis, mildiu y manchas en hortalizas, frutales y cítricos.", "bact mild manch"),
 "cuaternario_amonio": ("Desinfección de herramientas y superficies; algunas bacteriosis.", "bact"),
 "difenoconazol": ("Manchas, oídio y roya en hortalizas, frutales y soja; semillas.", "manch oidio roya suelf"),
 "diniconazol": ("Manchas y oídio.", "manch oidio"),
 "epoxiconazol": ("Roya y manchas en soja y cereales.", "roya manch"),
 "estreptomicina": ("Bacteriosis en hortalizas y frutales.", "bact"),
 "fenpropidina": ("Roya y oídio en cereales y soja.", "roya oidio"),
 "fenpropimorf": ("Roya asiática y oídio (socio de DMI y SDHI).", "roya oidio"),
 "fentin": ("Manchas y tizón tardío.", "manch mild"),
 "fluazinam": ("Moho blanco, tizón tardío y hongos de suelo.", "scle mild suelf"),
 "fludioxonil": ("Tratamiento de semillas y postcosecha (Fusarium, Rhizoctonia, Botrytis).", "suelf podr"),
 "fluindapir": ("Manchas y roya (SDHI).", "manch roya"),
 "fluopiram": ("Manchas, moho blanco y nematodos.", "manch scle nema"),
 "flutriafol": ("Roya y manchas en soja.", "roya manch"),
 "fluxapiroxad": ("Roya y manchas en soja, maíz y trigo.", "roya manch"),
 "folpet": ("Multisitio protector: mildiu y manchas en vid y hortalizas.", "mild manch"),
 "glucano": ("Inductor de defensas (bioinsumo).", "manch"),
 "hexaconazol": ("Manchas y oídio.", "manch oidio"),
 "inpyrfluxam": ("Roya asiática y manchas en soja (SDHI).", "roya manch"),
 "ipconazol": ("Tratamiento de semillas.", "suelf"),
 "isopirazam": ("Manchas y roya (SDHI).", "manch roya"),
 "isoprotiolano": ("Brusone del arroz.", "piri"),
 "kasugamicina": ("Bacteriosis y brusone.", "bact piri"),
 "kresoxim": ("Oídio y manchas en frutales y hortalizas.", "oidio manch"),
 "mancozeb": ("Multisitio protector: roya asiática, manchas, mildiu y antracnosis; principal socio antirresistencia.", "roya manch mild antr"),
 "mefentrifluconazol": ("Roya y manchas en soja y cereales (DMI nuevo).", "roya manch"),
 "metalaxil": ("Oomicetos: Pythium, Phytophthora y mildiu; semillas.", "mild suelf"),
 "metalaxil_m": ("Oomicetos: Pythium, Phytophthora y mildiu; semillas.", "mild suelf"),
 "metarilpicoxamida": ("Manchas y roya (QiI, molécula nueva).", "manch roya"),
 "metconazol": ("Roya, manchas y fusariosis.", "roya manch"),
 "metiltetraprol": ("Manchas y roya (QoI sin resistencia cruzada con estrobilurinas).", "manch roya"),
 "metominostrobina": ("Roya y manchas en soja.", "roya manch"),
 "nano_plata": ("Bacteriosis y hongos (desinfectante).", "bact"),
 "oxatiapiprolina": ("Mildiu y Phytophthora en hortalizas y vid.", "mild"),
 "oxitetraciclina": ("Bacteriosis en hortalizas y frutales.", "bact"),
 "penflufen": ("Tratamiento de semillas: Rhizoctonia.", "suelf"),
 "peptido_flg22": ("Inductor de defensas (bioinsumo).", "manch"),
 "percarbonato": ("Desinfectante oxidante.", "bact"),
 "physcion": ("Inductor de defensas (oídio).", "oidio"),
 "picoxistrobina": ("Roya y manchas en soja y maíz.", "roya manch"),
 "pidiflumetofen": ("Manchas y moho blanco (SDHI).", "manch scle"),
 "piraclostrobina": ("Roya, manchas y antracnosis en soja, maíz y hortalizas.", "roya manch antr"),
 "propiconazol": ("Roya y manchas en cereales, soja y frutales.", "roya manch"),
 "protioconazol": ("Roya asiática, manchas y fusariosis (DMI muy usado en soja).", "roya manch"),
 "reynoutria": ("Oídio y manchas (extracto vegetal).", "oidio manch"),
 "sedaxano": ("Tratamiento de semillas: Rhizoctonia.", "suelf"),
 "tebuconazol": ("Roya, manchas y fusariosis en soja, cereales y frutales.", "roya manch oidio"),
 "tetraconazol": ("Roya y oídio.", "roya oidio"),
 "tiabendazol": ("Semillas y postcosecha.", "suelf podr"),
 "tiofanato": ("Manchas, antracnosis y moho blanco; semillas.", "manch antr scle suelf"),
 "tiram": ("Multisitio para semillas y algunas manchas.", "suelf manch"),
 "triadimefon": ("Oídio y roya.", "oidio roya"),
 "triadimenol": ("Tratamiento de semillas y oídio.", "suelf oidio"),
 "triciclazol": ("Brusone del arroz.", "piri"),
 "trifloxistrobina": ("Roya, manchas y oídio en soja, maíz y frutales.", "roya manch oidio"),
 # ---------------- INSECTICIDAS ----------------
 "abamectina": ("Ácaros, minadores y trips en hortalizas y frutales; nematodos en semillas.", "acar minad trips nema"),
 "acefato": ("Chinches, trips, pulgones y lagartas (sistémico).", "chin trips pulg lag"),
 "acetamiprid": ("Mosca blanca, pulgones y chinches.", "mbla pulg chin"),
 "alfacipermetrina": ("Lagartas y chinches.", "lag chin"),
 "azadiractina": ("Lagartas, mosca blanca y pulgones (botánico).", "lag mbla pulg"),
 "benfuracarb": ("Plagas de suelo e insectos de inicio en semillas.", "suelo"),
 "betaciflutrina": ("Lagartas, chinches y picudo.", "lag chin coleo"),
 "bifentrina": ("Chinches, lagartas, ácaros y plagas de suelo; termitas.", "chin lag acar suelo term"),
 "buprofezina": ("Mosca blanca y cochinillas.", "mbla cochi"),
 "cadusafos": ("Nematodos y plagas de suelo.", "nema suelo"),
 "carbaril": ("Lagartas y coleópteros.", "lag coleo"),
 "carbosulfan": ("Pulgones y plagas de suelo; semillas.", "pulg suelo"),
 "cartap": ("Lagartas y minadores.", "lag minad"),
 "ciantraniliprol": ("Lagartas, mosca blanca y minadores.", "lag mbla minad"),
 "cihalodiamida": ("Lagartas.", "lag"),
 "cipermetrina": ("Lagartas y chinches.", "lag chin"),
 "ciproflanilida": ("Lagartas (molécula nueva).", "lag"),
 "clorantraniliprol": ("Lagartas en soja, maíz, algodón y hortalizas.", "lag"),
 "clorfenapir": ("Lagartas y ácaros.", "lag acar"),
 "clorpirifos": ("Plagas de suelo, lagartas y chinches.", "suelo lag chin"),
 "clorpirifos_metil": ("Plagas de granos almacenados.", "alm"),
 "clotianidina": ("Chinches, pulgones y plagas iniciales (semillas).", "chin pulg suelo"),
 "deltametrina": ("Lagartas, chinches y plagas de granos almacenados.", "lag chin alm"),
 "diafentiuron": ("Mosca blanca y ácaros.", "mbla acar"),
 "diatomeas": ("Plagas de granos almacenados (acción física).", "alm"),
 "diclorvos": ("Plagas de depósitos y almacenes.", "alm"),
 "dicofol": ("Ácaros.", "acar"),
 "diflubenzuron": ("Lagartas defoliadoras y langostas.", "lag lang"),
 "dimetoato": ("Pulgones, chinches y trips.", "pulg chin trips"),
 "dinotefuran": ("Chinches y mosca blanca.", "chin mbla"),
 "emamectina": ("Lagartas (Helicoverpa, Spodoptera).", "lag"),
 "esfenvalerato": ("Lagartas y chinches.", "lag chin"),
 "espidoxamato": ("Pulgones y mosca blanca (molécula nueva).", "pulg mbla"),
 "espinetoram": ("Lagartas, trips y minadores.", "lag trips minad"),
 "espinosad": ("Lagartas, trips y plagas de almacenes.", "lag trips alm"),
 "espirotetramato": ("Pulgones, mosca blanca y cochinillas.", "pulg mbla cochi"),
 "etiprol": ("Chinches y chicharritas.", "chin chich"),
 "fenpropatrina": ("Ácaros y lagartas.", "acar lag"),
 "fipronil": ("Hormigas cortadoras (cebo), plagas de suelo, picudo y termitas.", "horm suelo coleo term"),
 "flubendiamida": ("Lagartas.", "lag"),
 "flufenoxuron": ("Ácaros y lagartas.", "acar lag"),
 "fluxametamida": ("Lagartas y trips.", "lag trips"),
 "fosfuros": ("Fumigación de granos almacenados.", "alm"),
 "gammacialotrina": ("Lagartas y chinches.", "lag chin"),
 "hexitiazox": ("Ácaros (huevos y ninfas).", "acar"),
 "imidacloprid": ("Chinches, pulgones, mosca blanca y plagas iniciales.", "chin pulg mbla suelo"),
 "indoxacarb": ("Lagartas.", "lag"),
 "isocycloseram": ("Lagartas, trips y ácaros (molécula nueva).", "lag trips acar"),
 "isoflualanam": ("Molécula nueva: verificar etiqueta.", "lag"),
 "lambdacialotrina": ("Lagartas, chinches, salivazo y langostas.", "lag chin chich lang"),
 "lufenuron": ("Lagartas.", "lag"),
 "malation": ("Pulgones, mosca de la fruta y plagas de almacenes.", "pulg alm"),
 "matrina": ("Lagartas y pulgones (botánico).", "lag pulg"),
 "metomil": ("Lagartas y pulgones.", "lag pulg"),
 "metoxifenozida": ("Lagartas.", "lag"),
 "novaluron": ("Lagartas.", "lag"),
 "permetrina": ("Plagas de almacenes y hortalizas.", "alm lag"),
 "pimetrozina": ("Pulgones y mosca blanca.", "pulg mbla"),
 "pirimicarb": ("Pulgones.", "pulg"),
 "pirimifos_metil": ("Plagas de granos almacenados.", "alm"),
 "piriproxifen": ("Mosca blanca y cochinillas.", "mbla cochi"),
 "profenofos": ("Lagartas y chinches.", "lag chin"),
 "propargita": ("Ácaros.", "acar"),
 "rotenona": ("Insectos varios (botánico).", "pulg lag"),
 "spirodiclofen": ("Ácaros.", "acar"),
 "spiromesifen": ("Mosca blanca y ácaros.", "mbla acar"),
 "spiropidion": ("Pulgones, mosca blanca y ácaros (molécula nueva).", "pulg mbla acar"),
 "sulfluramida": ("Hormigas cortadoras (cebo).", "horm"),
 "sulfoxaflor": ("Chinches, pulgones y mosca blanca.", "chin pulg mbla"),
 "teflubenzuron": ("Lagartas.", "lag"),
 "tetradifon": ("Ácaros.", "acar"),
 "tiametoxam": ("Chinches, pulgones, mosca blanca y plagas iniciales (semillas).", "chin pulg mbla suelo"),
 "tiodicarb": ("Lagartas y plagas iniciales (semillas).", "lag suelo"),
 "triflumuron": ("Lagartas.", "lag"),
 "zetacipermetrina": ("Lagartas y chinches.", "lag chin"),
 # ---------------- OTROS ----------------
 "metaldehido": ("Caracoles y babosas (cebo).", "molu"),
 "cloquintocet": ("Protector de trigo para graminicidas.", "prot"),
 "dietholate": ("Protector de semillas frente a clomazona.", "prot"),
 "fluxofenim": ("Protector de sorgo frente a cloroacetamidas.", "prot"),
 "aba": ("Regulador: maduración y color de frutos.", "regu"),
 "auxinas_reg": ("Regulador: enraizamiento y cuaje.", "regu"),
 "brasinoesteroide": ("Regulador: estrés y crecimiento.", "regu"),
 "citocininas": ("Regulador: división celular y crecimiento.", "regu"),
 "clormequat": ("Regulador: acorta entrenudos (trigo, algodón).", "regu"),
 "etefon": ("Regulador: maduración, apertura de cápsulas y floración.", "regu"),
 "flumetralin": ("Regulador: control de brotes en tabaco.", "regu"),
 "giberelico": ("Regulador: crecimiento y cuaje.", "regu"),
 "mepiquat": ("Regulador de crecimiento en algodón.", "regu"),
 "tidiazuron": ("Defoliante de algodón y regulador.", "regu"),
 "trinexapac": ("Regulador: antivuelco en trigo y maduración en caña.", "regu"),
 "flocoumafen": ("Roedores (cebo anticoagulante).", "roed"),
 "pbo": ("Sinergista de piretroides.", "sine"),
 "feromona": ("Confusión sexual y monitoreo de plagas.", "lag"),
 # ---------------- BIOLÓGICOS ----------------
 "bio_bt": ("Lagartas (Bacillus thuringiensis).", "lag"),
 "bio_bacillus": ("Enfermedades foliares y de suelo; nematodos (Bacillus).", "manch suelf nema"),
 "bio_pseudomonas": ("Enfermedades de suelo y promotor de crecimiento.", "suelf"),
 "bio_trichoderma": ("Hongos de suelo y moho blanco (Trichoderma).", "suelf scle"),
 "bio_hongo_entomo": ("Mosca blanca, chinches, salivazo y lagartas (Beauveria, Metarhizium, Cordyceps).", "mbla chin chich lag"),
 "bio_virus": ("Lagartas (baculovirus).", "lag"),
 "bio_consorcio": ("Enfermedades de suelo y nutrición (consorcio microbiano).", "suelf"),
 "bio_macro": ("Control biológico con insectos benéficos.", "lag mbla"),
 "bot_extractos": ("Insectos y enfermedades varias (extractos botánicos).", "pulg manch"),
}

# Resistencias confirmadas o frecuentes en Paraguay y la región, por grupo de modo de acción.
RESISTENCIA = {
 "HRAC 9": "Glifosato: resistencia confirmada en Paraguay en capim amargoso (Digitaria insularis, desde 2005; con resistencia múltiple a glifosato + graminicidas en Hernandarias, 2020), buva (Conyza), caruru (Amaranthus), pata de gallina (Eleusine indica) y raigrás.",
 "HRAC 1": "Graminicidas ACCasa (cletodim, haloxifop): capim amargoso con resistencia múltiple a glifosato y ACCasa en Paraguay (2020); raigrás y pata de gallina en la región.",
 "HRAC 2": "ALS (sulfonilureas, imidazolinonas, diclosulam, cloransulam): caruru, buva y lecherón con resistencia en la región; poco efectivo solo.",
 "HRAC 22": "Paraquat: buva (Conyza sumatrensis) con resistencia múltiple a paraquat, glifosato y clorimuron reportada en Brasil.",
 "HRAC 4": "Auxinas: casos aislados en la región; cuidar deriva y volatilidad.",
 "HRAC 14": "PPO: caruru resistente en EE. UU. y Argentina; usar dosis plena y mezclar.",
 "FRAC 3": "DMI (triazoles): roya asiática con menor sensibilidad (mutaciones CYP51) en Paraguay y Brasil; no usar solos.",
 "FRAC 11": "QoI (estrobilurinas): roya asiática con mutación F129L en Paraguay y Brasil; usar siempre en mezcla y con multisitio.",
 "FRAC 7": "SDHI (carboxamidas): roya asiática con mutación SDHC-I86F en la región; máximo 2 aplicaciones por ciclo y siempre en mezcla.",
 "FRAC 1": "Bencimidazoles (carbendazim, tiofanato): resistencia extendida en muchos hongos; usar en mezcla.",
 "IRAC 3A": "Piretroides: Helicoverpa armigera, Spodoptera frugiperda y chinches (Euschistus heros) con resistencia o baja eficacia en la región.",
 "IRAC 1A": "Carbamatos: resistencia en Spodoptera y pulgones en la región.",
 "IRAC 1B": "Organofosforados: chinches y Spodoptera con resistencia en la región.",
 "IRAC 28": "Diamidas: casos de resistencia en Spodoptera frugiperda y Plutella; no más de 2 aplicaciones seguidas por generación.",
 "IRAC 15": "Benzoilureas: resistencia de Spodoptera frugiperda a lufenuron reportada en Brasil.",
 "IRAC 4A": "Neonicotinoides: mosca blanca y pulgones con resistencia en la región.",
 "IRAC 6": "Avermectinas: ácaros y Spodoptera con menor sensibilidad en algunas zonas.",
}

PRINCIPIOS_ROTACION = [
 "Rotar grupos de modo de acción (el número HRAC, IRAC o FRAC), no marcas: dos productos con distinto nombre y el mismo grupo cuentan como el mismo.",
 "Insectos: aplicar una 'ventana' de modo de acción por generación de la plaga (unos 30 días) y cambiar de grupo en la siguiente.",
 "Fungicidas de riesgo (DMI, QoI, SDHI): siempre en mezcla con otro modo de acción eficaz y con un multisitio (mancozeb, clorotalonil, cobre); máximo 2 aplicaciones de SDHI y de QoI por ciclo.",
 "Herbicidas: combinar 2 modos de acción eficaces sobre la misma maleza en cada aplicación, sumar preemergentes residuales y no depender solo de glifosato.",
 "Usar siempre la dosis de etiqueta: las subdosis seleccionan individuos resistentes.",
 "Integrar con medidas no químicas: rotación de cultivos, cobertura, refugio en cultivos Bt, monitoreo y umbrales.",
]
