# Problemas durante y después de la aplicación, reglas que los conectan con el semáforo y síntomas de diagnóstico.
# Agregado el 06/10/2026 a pedido de Diego: "que estén todos los problemas posibles en el caldo y durante la aplicación".
# Fuentes principales: GRDC (inversiones, calidad de pulverización, Delta T), Iowa State y NDSU (inversiones),
# AHRI-UWA y UNH (estrés hídrico), BCG y Bayer Canadá (heladas), Canola Council (polvo, anegamiento),
# Mississippi Soybean (rocío), BASF Francia (impactos/cm²), Sprayers101 (papel hidrosensible),
# Univ. de Wyoming (desgaste de picos), Mississippi State (CV), PNW 591 (abejas), Ley 3742/09 (arts. 24, 30, 45-48, 64-68, 72),
# Res. GMC 15/16 (LMR MERCOSUR), CASAFE y CAFYF (productos ilegales), Purdue PPP-142 (almacenamiento), Penn State (sobrantes).

CATEGORIA_APLICACION = ("Durante y después de la aplicación: el caldo está bien en el tanque, pero el producto no llega al blanco, "
                        "no actúa, se pierde o daña a personas, abejas, cultivos vecinos, el agua o el cultivo siguiente.")
# Problemas existentes que pasan a esta categoría
A_APLICACION = ["PR32", "PR33", "PR17"]
# PR33 queda solo para la evaporación; el lavado por lluvia pasa a PR35
RENOMBRAR = {
 "PR33": {"nombre": "Evaporación de las gotas antes de llegar al blanco",
          "que_es": "Con calor y aire seco las gotas pierden agua en el camino: se achican, derivan más y parte del producto no llega a la hoja.",
          "mecanismo": "Con Delta T alto (calor y aire seco) una gota fina se evapora en segundos; con volumen bajo y gota fina la pérdida es mayor.",
          "como_se_ve": ["Control irregular o malo sin problemas en el tanque", "Más deriva de lo habitual", "Tarjetas hidrosensibles con pocas gotas y muy chicas"],
          "causas": ["Delta T mayor a 8", "Humedad menor a 60 %", "Volumen bajo con gota fina", "Horas de más calor"],
          "productos_y_condiciones_de_riesgo": "Todos los productos foliares, en especial con gota fina, drone o avión.",
          "prevencion": ["Aplicar con Delta T entre 2 y 8", "Antievaporante o aceite según etiqueta", "Gota media a gruesa y volumen adecuado", "Horas frescas"],
          "que_hacer_si_ocurre": ["Suspender en las horas de calor", "Evaluar el control a los días indicados en la etiqueta"],
          "reglas_relacionadas": ["AMB01", "DR04", "EV01", "EV02"]},
}
# Reglas existentes: cambio de problemas asociados
REGLAS_PROBLEMAS = {"LL01": ["PR35"], "LL02": ["PR35"], "DR05": ["PR32", "PR34"], "EV03": ["PR32", "PR34"], "DR04": ["PR32", "PR33", "PR37"],
                    "C02": ["PR28", "PR47"], "DR03": ["PR32", "PR30", "PR36"]}

def _p(id_, nombre, que_es, mecanismo, como_se_ve, causas, riesgo, prevencion, que_hacer, reglas, cat="aplicacion"):
    return {"id": id_, "nombre": nombre, "categoria": cat, "que_es": que_es, "mecanismo": mecanismo, "como_se_ve": como_se_ve,
            "causas": causas, "productos_y_condiciones_de_riesgo": riesgo, "prevencion": prevencion,
            "que_hacer_si_ocurre": que_hacer, "reglas_relacionadas": reglas}

PROBLEMAS_APLICACION = [
 _p("PR34", "Inversión térmica",
    "Una capa de aire frío queda pegada al suelo y otra más caliente encima: el aire no se mezcla y las gotas finas quedan flotando y se desplazan kilómetros.",
    "De noche el suelo se enfría y enfría el aire de abajo. Las gotas de 200 µm o menos caen apenas unos centímetros por segundo y, sin turbulencia, quedan en una nube concentrada que se mueve con la brisa horas después. De noche con inversión puede quedar en el aire hasta 5 veces más producto (GRDC).",
    ["Niebla, rocío o escarcha", "Humo o polvo que queda a ras del suelo o se mueve de costado", "Calma total al amanecer o al atardecer con cielo despejado", "Ruidos y olores lejanos que se oyen o sienten más claro", "Daño en cultivos lejanos días después"],
    ["Aplicar de noche, al amanecer o al atardecer (de 1 a 2 h antes de la puesta del sol hasta 1 a 2 h después de la salida)", "Viento menor a 5 km/h medido a 2 m", "Cielo despejado (nubosidad de 25 % o menos)"],
    "Todos los productos con gota fina; muy grave con hormonales (2,4-D, dicamba), glifosato y desecantes cerca de cultivos sensibles.",
    ["Prueba del humo: si queda a ras del suelo o se mueve de costado, no aplicar", "Esperar viento constante de 3 a 10 km/h y sol que caliente el suelo", "Gota gruesa o muy gruesa (las etiquetas de 2,4-D la exigen)", "Usar el pronóstico de la app: marca las horas con inversión"],
    ["Suspender la aplicación", "Registrar hora, viento y productos", "Avisar a los vecinos con cultivos sensibles"],
    ["DR05", "EV03", "INV01"]),
 _p("PR35", "Lavado por lluvia o riego",
    "La lluvia o el riego sacan el producto de la hoja antes de que se absorba o se seque.",
    "Cada producto necesita horas sin lluvia: glifosato y 2,4-D amina hasta 6 h, bentazona 8 h, mancozeb unas 4 h, paraquat 30 min. Los de contacto y los polvos mojables se lavan más; las sales potásicas y los aceites se absorben más rápido.",
    ["Fallas después de una lluvia", "Control parejo pero débil en todo el lote"],
    ["Lluvia antes del período libre de lluvia de la etiqueta", "Riego por aspersión poco después de aplicar"],
    "Productos foliares; no afecta a los preemergentes, que necesitan lluvia para activarse.",
    ["Mirar el pronóstico de la app y elegir una ventana con horas sin lluvia por delante", "Respetar el período libre de lluvia de la etiqueta", "Adherente o aceite según etiqueta (ayuda poco)"],
    ["Consultar la etiqueta antes de repetir: no reaplicar a ciegas", "Evaluar el control a los días indicados"],
    ["LL01", "LL02"]),
 _p("PR36", "Escurrimiento y pérdida al suelo",
    "El caldo chorrea de las hojas y cae al suelo: menos producto en el blanco.",
    "El depósito sobre la hoja aumenta con el volumen solo hasta que la hoja empieza a chorrear; desde ahí baja. Los organosiliconados hacen que la gota se extienda tanto que con volumen alto escurre: en frutales y hortalizas pulverizados a punto de goteo, sus etiquetas piden cerca de 25 % del volumen habitual.",
    ["Hojas que gotean después de la pasada", "Charcos o suelo mojado bajo las plantas", "Control débil con volúmenes altos"],
    ["Volumen excesivo para el tamaño de las plantas", "Organosiliconado con volumen alto", "Hojas ya mojadas por rocío o lluvia", "Gota gruesa sobre hojas lisas"],
    "Organosiliconados, aceites a dosis alta; frutales y hortalizas pulverizados \"a punto de goteo\".",
    ["Ajustar el volumen al follaje", "Con organosiliconado, bajar el volumen o la dosis del organosiliconado según su etiqueta", "Esperar a que se seque el rocío"],
    ["Bajar el volumen o la dosis del tensioactivo en la próxima aplicación"],
    ["RU01", "ES03"]),
 _p("PR37", "Cobertura insuficiente del blanco",
    "Llegan pocas gotas por centímetro cuadrado o no llegan a la parte de la planta donde está la plaga o la enfermedad.",
    "La cobertura depende del volumen, el tamaño de gota, la velocidad, la altura y el follaje. Referencias de impactos por cm² en papel hidrosensible: sistémicos 20 a 30, insecticidas 30 a 50, fungicidas de contacto 50 a 70 (BASF).",
    ["Fallas en el interior del canopeo o en la cara inferior de las hojas", "Tarjetas hidrosensibles con pocos impactos", "Control bueno arriba y malo abajo"],
    ["Volumen bajo", "Gota demasiado gruesa para un producto de contacto", "Velocidad alta", "Canopeo cerrado", "Gota que se evapora antes de llegar"],
    "Fungicidas e insecticidas de contacto; drones y aviones con poco volumen.",
    ["Poner tarjetas hidrosensibles en distintas alturas del cultivo (con guantes; por encima de unos 100 L/ha las gotas se juntan)", "Ajustar volumen y gota al producto", "Bajar la velocidad en canopeos cerrados"],
    ["Revisar las tarjetas y corregir volumen, pastilla o velocidad", "Evaluar si hace falta reaplicar según la etiqueta"],
    ["DR04", "DRN02"]),
 _p("PR38", "Distribución despareja: franjas, superposición y fallas",
    "La dosis cambia a lo ancho o a lo largo del lote: franjas con sobredosis y franjas sin producto.",
    "Picos gastados o tapados, barra que rebota o está alta, superposición en cabeceras, pasadas mal alineadas o velocidad variable cambian la dosis. El CV entre picos debería quedar en 10 % o menos y en el campo en 15 % o menos; el rebote de la barra puede duplicar la variación.",
    ["Franjas más verdes o más dañadas siguiendo las pasadas", "Cabeceras con fitotoxicidad", "Fallas entre pasadas"],
    ["Picos con 10 % más caudal que uno nuevo", "Equipo sin calibrar", "Barra alta o que rebota", "Sin corte de secciones en cabeceras", "Pasadas sin guía"],
    "Herbicidas (fitotoxicidad por sobredosis en superposición); todos los productos en las franjas de falla.",
    ["Calibrar el equipo y cambiar los picos gastados", "Barra a la altura justa (unos 50 cm con picos de 110° cada 50 cm)", "Guía satelital y corte de secciones", "Velocidad pareja"],
    ["Recalibrar antes de seguir", "Marcar en el mapa las franjas con problemas para evaluarlas"],
    ["EQ01"]),
 _p("PR39", "Hojas mojadas o con polvo",
    "El rocío diluye o hace chorrear el caldo; el polvo sobre la hoja atrapa al glifosato, el paraquat y el diquat y los deja sin efecto.",
    "El glifosato y el diquat se fijan a las partículas de suelo; el polvo depositado antes o hasta 15 min después de aplicar redujo el control con glifosato. El rocío casi no afecta salvo que la hoja chorree.",
    ["Mal control en bordes de caminos y cabeceras con polvo", "Hojas que gotean al aplicar con rocío"],
    ["Caminos de tierra, viento con polvo o sequía", "Equipo que levanta polvo", "Rocío abundante a primera hora"],
    "Glifosato, paraquat y diquat con polvo; cualquier producto con hojas chorreando.",
    ["Con polvo: más volumen, dosis alta en los bordes de caminos, menor velocidad y agua limpia", "Con rocío: esperar a que las hojas no chorreen"],
    ["Evaluar los bordes con polvo y repasarlos si hace falta"],
    ["ES03", "ES04"]),
 _p("PR40", "Plantas estresadas: sequía, calor, helada o anegamiento",
    "La maleza o el cultivo estresado absorbe y mueve poco el producto; el cultivo estresado es más sensible a la fitotoxicidad.",
    "Con sequía la planta forma una cutícula más gruesa y transloca menos: los sistémicos como el glifosato pierden mucha eficacia, y la cutícula sigue aunque llueva (hay que esperar hojas nuevas). Después de una helada las plantas paran de crecer: graminicidas, 1 día de espera por cada helada; glifosato con helada fuerte (menos de −5 °C), 1 a 2 días y reanudar con máxima de 8 °C o más. El cultivo anegado es más sensible al herbicida.",
    ["Malezas que sobreviven a la dosis de etiqueta", "Control lento o parcial", "Fitotoxicidad mayor a la habitual en el cultivo"],
    ["Sequía o calor prolongado", "Helada en los últimos días", "Suelo anegado", "Malezas grandes o endurecidas"],
    "Herbicidas sistémicos (glifosato, hormonales, graminicidas, ALS); herbicidas selectivos sobre el cultivo estresado.",
    ["Aplicar cuando las plantas se recuperan (después de una lluvia, con hojas nuevas)", "Horas frescas y dosis plena de etiqueta", "No subir la dosis sobre el cultivo estresado"],
    ["Evaluar el control y planificar un segundo control con otro modo de acción si hace falta"],
    ["ES01", "ES02", "ES05"]),
 _p("PR41", "Momento inadecuado de la aplicación",
    "Se aplica cuando la maleza está muy grande, la plaga fuera de su estadio sensible o el cultivo en un estadio que la etiqueta no permite.",
    "Cada producto tiene un estadio de máxima eficacia (malezas chicas, larvas pequeñas, preventivo en enfermedades) y estadios del cultivo autorizados. Fuera de ese momento la dosis de etiqueta no alcanza o daña el cultivo.",
    ["Malezas grandes que rebrotan", "Plaga que sigue activa", "Daño en el cultivo por aplicar fuera del estadio autorizado"],
    ["Demora en la aplicación", "No respetar el umbral de daño ni el estadio de la etiqueta"],
    "Todos.",
    ["Monitorear y aplicar en el estadio que indica la etiqueta", "Respetar los umbrales de acción"],
    ["Evaluar y planificar el control siguiente con otro modo de acción"],
    []),
 _p("PR42", "Falla por resistencia (repetir el mismo modo de acción)",
    "La plaga, enfermedad o maleza ya no se controla con el producto porque la población se volvió resistente.",
    "Repetir el mismo grupo HRAC, IRAC o FRAC selecciona a los individuos resistentes. En Paraguay hay malezas resistentes a glifosato, ALS y otros grupos.",
    ["Manchones que sobreviven en los mismos lugares cada campaña", "Plantas vivas al lado de muertas de la misma especie"],
    ["Mismo modo de acción varias veces por campaña", "Dosis bajas", "Sin control con otros métodos"],
    "Herbicidas ALS, glifosato, graminicidas; insecticidas piretroides y diamidas; fungicidas de sitio único.",
    ["Rotar y combinar modos de acción (pestaña Rotación)", "Usar la dosis de etiqueta", "Sumar control cultural"],
    ["No repetir el mismo producto: cambiar de grupo", "Mandar a analizar las plantas sospechosas"],
    []),
 _p("PR43", "Daño a abejas y fauna benéfica",
    "Insecticidas tóxicos para las abejas matan a las que pecorean en el lote o en las malezas en flor, y a los enemigos naturales de las plagas.",
    "Neonicotinoides (IRAC 4A), fipronil (2B), piretroides (3A), organofosforados (1B), carbamatos (1A), abamectina y emamectina (6), sulfoxaflor (4C) e indoxacarb (22A) son altamente tóxicos; espinosinas (5), clorfenapir (13), acetamiprid y novalurón son tóxicos (las espinosinas, por pocas horas). Los microencapsulados, los polvos y los WP son los más peligrosos. Las etiquetas lo indican (por ejemplo \"Abejas: altamente tóxico\").",
    ["Abejas muertas frente a las colmenas", "Colmenas debilitadas después de una aplicación", "Rebrote de plagas por falta de enemigos naturales"],
    ["Aplicar sobre floración del cultivo o de las malezas", "Aplicar con abejas pecoreando", "Deriva hacia colmenas"],
    "Insecticidas de los grupos IRAC 4A, 2B, 3A, 1A, 1B, 6, 4C y 22A (altamente tóxicos) y 5 y 13 (tóxicos).",
    ["No aplicar sobre floración, tampoco de malezas", "Aplicar al atardecer o de noche, cuando no pecorean", "Avisar a los apicultores con anticipación", "Elegir productos de menor toxicidad para abejas"],
    ["Registrar productos y hora", "Avisar al apicultor"],
    ["AB01", "AB02"]),
 _p("PR44", "Intoxicación o exposición del operario",
    "El aplicador o quien prepara el caldo se expone al producto por la piel, la boca o la respiración.",
    "La exposición es mayor al manipular el producto concentrado (carga del tanque) y con productos de clase toxicológica I (banda roja). La Ley 3742/09 (art. 64) obliga a usar equipo de protección.",
    ["Dolor de cabeza, náuseas, mareos, visión borrosa, sudoración, irritación de piel u ojos durante o después de aplicar"],
    ["Cargar sin guantes ni antiparras", "Aplicar sin equipo de protección", "Comer, beber o fumar sin lavarse", "Reingresar al lote antes de tiempo"],
    "Productos clase Ia y Ib (banda roja) y II (amarilla); fumigantes; paraquat.",
    ["Equipo de protección completo, sobre todo al cargar: ropa de manga larga, delantal impermeable, guantes de nitrilo, botas, antiparras y respirador con filtro", "Respetar el tiempo de reingreso de la etiqueta", "Ducha y ropa lavada aparte al terminar"],
    ["Retirar a la persona de la zona, sacarle la ropa contaminada y lavar la piel con abundante agua", "Llevar la etiqueta al médico", "Emergencias: 911. Centro Nacional de Toxicología: (021) 220-418 o (021) 204-800 (números de etiquetas registradas y de la prensa; confirmar en la etiqueta)"],
    ["TX01", "AMB01"]),
 _p("PR45", "Contaminación de agua, suelo y entorno (sobrantes, enjuagues y envases)",
    "Sobrantes de caldo, aguas de lavado o envases mal manejados llegan a cursos de agua, pozos o al suelo fuera del lote.",
    "La Ley 3742/09 fija franjas de protección: 100 m de cursos de agua y de asentamientos en aplicación terrestre; 200 m en aplicación aérea; barrera viva de 5 m o franja de 50 m junto a caminos vecinales poblados. Los equipos se cargan y lavan lejos del agua (art. 65); los envases van con triple lavado, perforados, al centro de acopio (art. 48).",
    ["Peces muertos o espuma en arroyos", "Manchas de vegetación muerta donde se lava el equipo"],
    ["Cargar o lavar el equipo cerca de agua", "Tirar el sobrante al suelo o a desagües", "Envases sin triple lavado o quemados"],
    "Todos; más los muy tóxicos para peces (piretroides, por ejemplo).",
    ["Calcular bien el caldo para que no sobre", "El sobrante y el primer enjuague se aplican sobre el lote ya tratado o un cultivo de la etiqueta, sin pasar la dosis", "Triple lavado de envases al vaciarlos: 1/4 de agua, agitar 30 s, volcar al tanque, 3 veces y perforar", "Respetar las franjas de la ley"],
    ["Contener el derrame con tierra o arena y avisar a la autoridad si llega al agua"],
    []),
 _p("PR46", "Residuos en la cosecha (carencia y LMR)",
    "El producto queda en el grano, la fruta o el forraje por encima del límite permitido.",
    "La etiqueta fija el tiempo de carencia (días entre la última aplicación y la cosecha o el pastoreo). El límite máximo de residuos (LMR) lo fija cada país comprador; en el MERCOSUR rige el del país importador o, si no tiene, el del Codex.",
    ["Rechazo del lote por análisis de residuos"],
    ["No respetar la carencia", "Dosis o número de aplicaciones mayor al de la etiqueta", "Producto no autorizado para ese cultivo"],
    "Todos; más los de aplicación cerca de cosecha (desecantes, fungicidas e insecticidas tardíos) y las hortalizas.",
    ["Respetar la carencia y el número máximo de aplicaciones de la etiqueta", "Registrar cada aplicación (fecha y producto)"],
    ["Consultar al comprador antes de cosechar"],
    []),
 _p("PR47", "Daño al cultivo siguiente (carry-over) o al pulverizado después",
    "Un herbicida que queda en el suelo o en el equipo daña al cultivo que se siembra o se pulveriza después.",
    "Los residuales (imidazolinonas, sulfonilureas, triazinas, HPPD, picloram) persisten en el suelo según la dosis, la lluvia y el pH; los hormonales y las sulfonilureas dejan restos en el equipo que dañan cultivos sensibles a dosis mínimas.",
    ["Cultivo que nace mal o con síntomas de herbicida", "Daño en la soja pulverizada con un equipo que tuvo 2,4-D o dicamba"],
    ["Sembrar antes del intervalo de la etiqueta", "Poca lluvia después del residual", "Equipo mal lavado"],
    "Residuales de suelo y hormonales; ver la sección Cultivos y carry-over.",
    ["Respetar los intervalos (la app los calcula)", "Triple lavado con el limpiador que corresponde (guía de limpieza)"],
    ["Registrar y consultar al técnico; en el equipo, repetir la limpieza"],
    ["C02"]),
 _p("PR48", "Producto ilegal, adulterado o en mal estado",
    "Productos sin registro, de contrabando, falsificados, vencidos o mal almacenados: no hacen efecto, dañan el cultivo o el equipo.",
    "La Ley 3742/09 considera fraudulentos a los productos sin registro (art. 24) y prohíbe los adulterados, vencidos o de contrabando (art. 72). El calor (más de 38 °C) y la helada deterioran las formulaciones: los SC se asientan y no se resuspenden, los EC forman cristales y los sólidos hacen grumos.",
    ["Tapa, precinto o etiqueta distintos a los habituales", "Sin número de registro SENAVE, lote o vencimiento", "Precio muy bajo o venta fraccionada", "En el bidón: capas que no se mezclan, cristales o grumos"],
    ["Compra sin factura", "Depósito caluroso o con heladas", "Producto vencido"],
    "Todos; más los de alto valor (son los más falsificados).",
    ["Comprar con factura a comercios habilitados y verificar el registro SENAVE (la app lo muestra)", "Guardar entre 4 y 25 °C", "Prueba del frasco: si se separa en 5 a 10 min y no se remezcla al agitar, no usar", "Si se congeló, descongelar a temperatura ambiente y agitar; si quedan cristales, no usar"],
    ["No usar el producto y avisar al SENAVE"],
    ["MV01"]),
 _p("PR49", "Error de dosis o de cálculo",
    "Se aplica más o menos producto del planeado por errores de cálculo, de medición o de superficie.",
    "Errores comunes: confundir L/ha con L por tanque, medir con recipientes no graduados, superficie mal medida, remanente del tanque no descontado o volumen real distinto del calibrado.",
    ["Sobra o falta caldo al terminar el lote", "Fitotoxicidad o control débil en todo el lote"],
    ["Cálculo a mano", "Equipo sin calibrar", "Cambio de volumen sin recalcular las dosis"],
    "Todos; los herbicidas sobre el cultivo y los productos de margen estrecho son los más delicados.",
    ["Usar la calculadora de dosis de la app (por hectárea y por tanque)", "Medir con jarras graduadas", "Calibrar y verificar que sobre o falte lo esperado"],
    ["Registrar la dosis real aplicada y evaluar el efecto"],
    ["EQ01"]),
 _p("PR50", "Grano húmedo, caliente o infestado (granos almacenados)",
    "El grano se guarda o se trata con humedad alta, caliente o ya con insectos: el protector dura menos, se forman hongos y la plaga sigue.",
    "Con más de 13 % de humedad el grano respira y se calienta; los insectos se multiplican rápido entre 25 y 32 °C. Mucha agua en el tratamiento (más de 1 a 1,5 L/t) sube la humedad. Un protector no controla una infestación ya instalada: para eso se fumiga.",
    ["Grano caliente o con olor a humedad", "Insectos vivos al calar", "CO₂ alto en el silo (más de 1100 ppm)"],
    ["Cosechar o guardar sin secar", "Sin aireación", "Tratar grano ya infestado", "Demasiado caldo por tonelada"],
    "Todos los granos; el maíz y el trigo son los más atacados por gorgojos y taladrillo.",
    ["Secar a 13 % o menos", "Airear para bajar la temperatura", "Limpiar y tratar el silo vacío antes de cargar", "Fumigar con fosfina si ya hay insectos y después proteger"],
    ["Fumigar en silo hermético con los tiempos de la etiqueta", "Bajar la humedad y la temperatura con aireación"],
    ["AL03", "AL04"]),
]

# Reglas nuevas (aplicación) y su semáforo
_SISTEMICOS_HELADA = ["glifosato", "24d", "dicamba", "triclopir", "picloram", "fluroxipir", "aminopiralida",
                      "cletodim", "haloxifop", "quizalofop", "propaquizafop", "fenoxaprop", "imazetapir", "clorimuron", "metsulfuron", "nicosulfuron"]
_POLVO = ["glifosato", "paraquat", "diquat"]
REGLAS_APLIC = [
 {"id": "INV01", "tipo": "deriva", "severidad": "alta",
  "titulo": "Inversión térmica probable: amanecer o atardecer, poco viento y cielo despejado",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"hora_inversion": {"==": True}, "viento_kmh": {"<": 8}, "nubosidad": {"en": ["Despejado"]}}},
  "mecanismo": "Con cielo despejado el suelo se enfría y el aire frío queda abajo: las gotas finas quedan flotando y viajan kilómetros con la brisa.",
  "recomendacion": "Hacer la prueba del humo; si queda a ras del suelo, no aplicar. Esperar viento constante de 3 a 10 km/h con sol.",
  "confianza": "media", "problemas": ["PR34", "PR32"]},
 {"id": "ES01", "tipo": "manejo", "severidad": "media",
  "titulo": "Plantas con estrés por sequía o calor: el herbicida se absorbe y transloca poco",
  "condiciones": {"presentes": [{"clase": ["herbicida"]}], "agua": {}, "caldo": {"estado_plantas": {"incluye_alguno": ["sequia"]}}},
  "mecanismo": "Con sequía la cutícula se engrosa y la planta mueve poca savia: los sistémicos pierden mucha eficacia y la cutícula sigue aunque llueva.",
  "recomendacion": "Aplicar cuando las plantas se recuperan (hojas nuevas después de una lluvia), en horas frescas y con dosis plena.",
  "confianza": "alta", "problemas": ["PR40"]},
 {"id": "ES02", "tipo": "manejo", "severidad": "media",
  "titulo": "Helada reciente: herbicidas sistémicos con poca eficacia",
  "condiciones": {"presentes": [{"ai": _SISTEMICOS_HELADA}], "agua": {}, "caldo": {"estado_plantas": {"incluye_alguno": ["helada"]}}},
  "mecanismo": "Después de una helada las plantas paran de crecer y no translocan el herbicida.",
  "recomendacion": "Graminicidas: esperar 1 día por cada helada. Glifosato: con helada leve se puede aplicar si se esperan 10 °C o más por 2 a 4 h; con helada fuerte (menos de −5 °C), esperar 1 a 2 días.",
  "confianza": "media", "problemas": ["PR40"]},
 {"id": "ES03", "tipo": "manejo", "severidad": "baja",
  "titulo": "Hojas mojadas por rocío o lluvia: dilución y escurrimiento",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"estado_plantas": {"incluye_alguno": ["mojadas"]}}},
  "mecanismo": "El agua sobre la hoja diluye el caldo y, si la hoja chorrea, el producto cae al suelo.",
  "recomendacion": "Esperar a que las hojas no chorreen.",
  "confianza": "media", "problemas": ["PR39", "PR36"]},
 {"id": "ES04", "tipo": "antagonismo", "severidad": "media",
  "titulo": "Polvo sobre las hojas con glifosato, paraquat o diquat",
  "condiciones": {"presentes": [{"ai": _POLVO}], "agua": {}, "caldo": {"estado_plantas": {"incluye_alguno": ["polvo"]}}},
  "mecanismo": "Las partículas de suelo fijan el glifosato y el diquat (y el paraquat) y los dejan sin efecto.",
  "recomendacion": "Más volumen, dosis alta en los bordes de caminos, menor velocidad para no levantar polvo y agua limpia.",
  "confianza": "alta", "problemas": ["PR39", "PR22"]},
 {"id": "ES05", "tipo": "fitotoxicidad", "severidad": "media",
  "titulo": "Cultivo anegado: más sensible al herbicida",
  "condiciones": {"presentes": [{"clase": ["herbicida"]}], "agua": {}, "caldo": {"estado_plantas": {"incluye_alguno": ["anegado"]}, "momento": {"en": ["post"]}}},
  "mecanismo": "El cultivo con raíces sin oxígeno metaboliza peor el herbicida y se daña más.",
  "recomendacion": "Esperar a que el suelo drene y el cultivo se recupere; no subir la dosis.",
  "confianza": "media", "problemas": ["PR40", "PR23"]},
 {"id": "RU01", "tipo": "manejo", "severidad": "media",
  "titulo": "Organosiliconado con volumen alto: escurrimiento",
  "condiciones": {"presentes": [{"adyuvante": ["ady_organosiliconado"]}], "agua": {}, "caldo": {"volumen_L_ha": {">": 200}}},
  "mecanismo": "El organosiliconado extiende tanto la gota que con mucho volumen la hoja chorrea y el producto cae al suelo.",
  "recomendacion": "Bajar el volumen o la dosis del organosiliconado según su etiqueta (en frutales a punto de goteo, cerca de 25 % del volumen habitual), o cambiar a un tensioactivo común.",
  "confianza": "media", "problemas": ["PR36"]},
 {"id": "AB01", "tipo": "ambiente", "severidad": "alta",
  "titulo": "Insecticida tóxico para abejas con floración o colmenas cerca",
  "condiciones": {"presentes": [{"ai": "__ABEJAS__"}], "agua": {}, "caldo": {"abejas": {"==": "si"}}},
  "mecanismo": "Los neonicotinoides, el fipronil, los piretroides, los organofosforados, los carbamatos, la abamectina y el sulfoxaflor matan a las abejas que pecorean el lote o las malezas en flor.",
  "recomendacion": "No aplicar sobre floración (tampoco de malezas); aplicar al atardecer sin abejas pecoreando y avisar a los apicultores.",
  "confianza": "alta", "problemas": ["PR43"]},
 {"id": "AB02", "tipo": "ambiente", "severidad": "media",
  "titulo": "Insecticida tóxico para abejas (espinosinas, clorfenapir, acetamiprid, novalurón) con floración o colmenas cerca",
  "condiciones": {"presentes": [{"ai": "__ABEJAS_MEDIO__"}], "agua": {}, "caldo": {"abejas": {"==": "si"}}},
  "mecanismo": "Son tóxicos para las abejas, aunque menos que los neonicotinoides o los piretroides; las espinosinas, por pocas horas después de secas.",
  "recomendacion": "Aplicar al atardecer, cuando las abejas no pecorean, y avisar a los apicultores.",
  "confianza": "media", "problemas": ["PR43"]},
 {"id": "TX01", "tipo": "seguridad", "severidad": "media",
  "titulo": "Producto de clase toxicológica I (banda roja): protección del operario",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"tox_alta": {"==": True}}},
  "mecanismo": "Los productos de banda roja son extremadamente o altamente peligrosos: la carga del concentrado es el momento de mayor exposición.",
  "recomendacion": "Equipo de protección completo (art. 64 Ley 3742/09) y respetar el reingreso de la etiqueta.",
  "confianza": "alta", "problemas": ["PR44"]},
 {"id": "EQ01", "tipo": "equipo", "severidad": "media",
  "titulo": "Equipo sin calibración vigente",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"equipo_sin_calibrar": {"==": True}}},
  "mecanismo": "Sin calibrar no se sabe cuánto se aplica: los picos gastados tiran más y la velocidad real cambia la dosis.",
  "recomendacion": "Calibrar en Equipos y calibración (velocidad, caudal de cada pico y volumen real) y cambiar los picos que tiran 10 % más que uno nuevo.",
  "confianza": "alta", "problemas": ["PR38", "PR49"]},
 {"id": "MV01", "tipo": "manejo", "severidad": "media",
  "titulo": "Producto con el mantenimiento del registro vencido",
  "condiciones": {"presentes": [], "agua": {}, "caldo": {"registro_vencido": {"==": True}}},
  "mecanismo": "El SENAVE lista el producto con el mantenimiento del registro vencido: puede no estar habilitado para la venta.",
  "recomendacion": "Verificar con el comercio o el SENAVE que el producto se pueda usar; preferir uno con registro vigente.",
  "confianza": "media", "problemas": ["PR48"]},
]
SEMAFORO_APLIC = {
 "INV01": [2, 2, {}],
 "ES01": [None, 1, {"dosisplena": 1, "horario": 1}],
 "ES02": [None, 0, {"esperar": 1}],
 "ES03": [None, 0, {"esperar": 1}],
 "ES04": [None, 0, {"polvo": 1}],
 "ES05": [None, 0, {"esperar": 1}],
 "RU01": [None, 0, {"menosvol": 1}],
 "AB01": [None, 0, {"abejas": 2}],
 "AB02": [None, 0, {"abejas": 1}],
 "TX01": [None, 0, {"epp": 1}],
 "EQ01": [None, 0, {"calibrar": 1}],
 "MV01": [None, 1, {}],
}
MEDIDAS_APLIC = {
 "esperar": {"tipo": "practica", "nombre": "Esperar a que las plantas se recuperen o se sequen",
             "detalle": "Después de una helada, 1 a 2 días; con rocío, hasta que las hojas no chorreen; con suelo anegado, hasta que drene y el cultivo retome el crecimiento."},
 "polvo": {"tipo": "practica", "nombre": "Manejo con polvo",
           "detalle": "Más volumen, dosis alta en los bordes de caminos, menor velocidad para no levantar polvo y agua limpia; mejor después de una lluvia."},
 "menosvol": {"tipo": "practica", "nombre": "Volumen acorde al organosiliconado",
              "detalle": "Bajar el volumen según la etiqueta del organosiliconado o cambiar a un tensioactivo común."},
 "abejas": {"tipo": "practica", "nombre": "Cuidado de las abejas",
            "detalle": "Sin floración (tampoco de malezas), al atardecer sin abejas pecoreando y con aviso previo a los apicultores."},
 "epp": {"tipo": "practica", "nombre": "Equipo de protección completo",
         "detalle": "Ropa de manga larga, delantal impermeable, guantes de nitrilo, botas, antiparras y respirador con filtro, sobre todo al cargar; ducha al terminar."},
 "calibrar": {"tipo": "practica", "nombre": "Calibrar antes de aplicar",
              "detalle": "Velocidad, caudal de cada pico y volumen real (Equipos y calibración)."},
}
# Insecticidas muy tóxicos para abejas (PNW 591): se toman de los activos por su grupo IRAC
# Altamente tóxicos (PNW 591)
IRAC_ABEJAS = ["IRAC 4A", "IRAC 2B", "IRAC 3A", "IRAC 1A", "IRAC 1B", "IRAC 6", "IRAC 4C", "IRAC 22A"]
# Tóxicos (menos que los anteriores o por poco tiempo): espinosinas, clorfenapir, acetamiprid, pirimicarb, novalurón
IRAC_ABEJAS_MEDIO = ["IRAC 5", "IRAC 13"]
ABEJAS_MEDIO_AI = ["acetamiprid", "pirimicarb", "novaluron"]
# cadusafos se aplica al suelo
ABEJAS_EXCLUIR = ["acetamiprid", "pirimicarb", "cadusafos"]

# Diagnóstico por síntoma: nuevos y agregados
DIAG_NUEVOS = [
 {"sintoma": "Niebla o gotas que quedan flotando al amanecer o al atardecer; daño en cultivos lejanos", "problemas": ["PR34", "PR32"]},
 {"sintoma": "Franjas con más y menos control o daño siguiendo las pasadas", "problemas": ["PR38", "PR37", "PR27"]},
 {"sintoma": "El caldo chorrea de las hojas", "problemas": ["PR36", "PR39"]},
 {"sintoma": "Malezas que sobreviven en plantas estresadas, después de una helada o con polvo", "problemas": ["PR40", "PR39", "PR41"]},
 {"sintoma": "Manchones que sobreviven en los mismos lugares cada campaña", "problemas": ["PR42", "PR38"]},
 {"sintoma": "Fallas después de una lluvia", "problemas": ["PR35"]},
 {"sintoma": "Abejas muertas o colmenas debilitadas cerca del lote", "problemas": ["PR43", "PR32"]},
 {"sintoma": "Dolor de cabeza, náuseas, mareos o irritación en quien aplicó", "problemas": ["PR44", "PR20"]},
 {"sintoma": "Producto con etiqueta rara, sin registro o precio muy bajo; capas, cristales o grumos en el bidón", "problemas": ["PR48", "PR03", "PR04"]},
 {"sintoma": "Rechazo del lote por residuos", "problemas": ["PR46"]},
 {"sintoma": "El cultivo siguiente nace mal o con síntomas de herbicida", "problemas": ["PR47", "PR28"]},
 {"sintoma": "Sobra o falta caldo al terminar el lote", "problemas": ["PR49", "PR38"]},
 {"sintoma": "Peces muertos o vegetación seca donde se carga o se lava el equipo", "problemas": ["PR45"]},
]
DIAG_AGREGAR = {"El caldo se ve normal": ["PR35", "PR37", "PR40", "PR42", "PR48"], "Más deriva o escurrimiento": ["PR34", "PR36"]}

ESTADO_PLANTAS = [["sequia", "Sequía o calor"], ["helada", "Helada reciente"], ["mojadas", "Hojas mojadas (rocío)"], ["polvo", "Hojas con polvo"], ["anegado", "Suelo anegado"]]
